// Code generated by protoc-gen-psrpc v0.7.0, DO NOT EDIT.
// source: rpc/connector.proto

package rpc

import (
	"context"

	"github.com/livekit/psrpc"
	"github.com/livekit/psrpc/pkg/client"
	"github.com/livekit/psrpc/pkg/info"
	"github.com/livekit/psrpc/pkg/rand"
	"github.com/livekit/psrpc/pkg/server"
	"github.com/livekit/psrpc/version"
)
import livekit10 "github.com/rezi-io/livekit-protocol/livekit"
import livekit11 "github.com/rezi-io/livekit-protocol/livekit"

var _ = version.PsrpcVersion_0_7

// ==================================
// ConnectorInternal Client Interface
// ==================================

type ConnectorInternalClient interface {
	DialWhatsAppCall(ctx context.Context, topic string, req *InternalDialWhatsAppCallRequest, opts ...psrpc.RequestOption) (*livekit10.DialWhatsAppCallResponse, error)

	AcceptWhatsAppCall(ctx context.Context, topic string, req *InternalAcceptWhatsAppCallRequest, opts ...psrpc.RequestOption) (*livekit10.AcceptWhatsAppCallResponse, error)

	ConnectTwilioCall(ctx context.Context, topic string, req *InternalConnectTwilioCallRequest, opts ...psrpc.RequestOption) (*livekit11.ConnectTwilioCallResponse, error)

	// Close immediately, without waiting for pending RPCs
	Close()
}

// ======================================
// ConnectorInternal ServerImpl Interface
// ======================================

type ConnectorInternalServerImpl interface {
	DialWhatsAppCall(context.Context, *InternalDialWhatsAppCallRequest) (*livekit10.DialWhatsAppCallResponse, error)

	AcceptWhatsAppCall(context.Context, *InternalAcceptWhatsAppCallRequest) (*livekit10.AcceptWhatsAppCallResponse, error)

	ConnectTwilioCall(context.Context, *InternalConnectTwilioCallRequest) (*livekit11.ConnectTwilioCallResponse, error)
}

// ==================================
// ConnectorInternal Server Interface
// ==================================

type ConnectorInternalServer interface {
	RegisterDialWhatsAppCallTopic(topic string) error
	DeregisterDialWhatsAppCallTopic(topic string)
	RegisterAcceptWhatsAppCallTopic(topic string) error
	DeregisterAcceptWhatsAppCallTopic(topic string)
	RegisterConnectTwilioCallTopic(topic string) error
	DeregisterConnectTwilioCallTopic(topic string)

	// Close and wait for pending RPCs to complete
	Shutdown()

	// Close immediately, without waiting for pending RPCs
	Kill()
}

// ========================
// ConnectorInternal Client
// ========================

type connectorInternalClient struct {
	client *client.RPCClient
}

// NewConnectorInternalClient creates a psrpc client that implements the ConnectorInternalClient interface.
func NewConnectorInternalClient(bus psrpc.MessageBus, opts ...psrpc.ClientOption) (ConnectorInternalClient, error) {
	sd := &info.ServiceDefinition{
		Name: "ConnectorInternal",
		ID:   rand.NewClientID(),
	}

	sd.RegisterMethod("DialWhatsAppCall", false, false, true, true)
	sd.RegisterMethod("AcceptWhatsAppCall", false, false, true, true)
	sd.RegisterMethod("ConnectTwilioCall", false, false, true, true)

	rpcClient, err := client.NewRPCClient(sd, bus, opts...)
	if err != nil {
		return nil, err
	}

	return &connectorInternalClient{
		client: rpcClient,
	}, nil
}

func (c *connectorInternalClient) DialWhatsAppCall(ctx context.Context, topic string, req *InternalDialWhatsAppCallRequest, opts ...psrpc.RequestOption) (*livekit10.DialWhatsAppCallResponse, error) {
	return client.RequestSingle[*livekit10.DialWhatsAppCallResponse](ctx, c.client, "DialWhatsAppCall", []string{topic}, req, opts...)
}

func (c *connectorInternalClient) AcceptWhatsAppCall(ctx context.Context, topic string, req *InternalAcceptWhatsAppCallRequest, opts ...psrpc.RequestOption) (*livekit10.AcceptWhatsAppCallResponse, error) {
	return client.RequestSingle[*livekit10.AcceptWhatsAppCallResponse](ctx, c.client, "AcceptWhatsAppCall", []string{topic}, req, opts...)
}

func (c *connectorInternalClient) ConnectTwilioCall(ctx context.Context, topic string, req *InternalConnectTwilioCallRequest, opts ...psrpc.RequestOption) (*livekit11.ConnectTwilioCallResponse, error) {
	return client.RequestSingle[*livekit11.ConnectTwilioCallResponse](ctx, c.client, "ConnectTwilioCall", []string{topic}, req, opts...)
}

func (s *connectorInternalClient) Close() {
	s.client.Close()
}

// ========================
// ConnectorInternal Server
// ========================

type connectorInternalServer struct {
	svc ConnectorInternalServerImpl
	rpc *server.RPCServer
}

// NewConnectorInternalServer builds a RPCServer that will route requests
// to the corresponding method in the provided svc implementation.
func NewConnectorInternalServer(svc ConnectorInternalServerImpl, bus psrpc.MessageBus, opts ...psrpc.ServerOption) (ConnectorInternalServer, error) {
	sd := &info.ServiceDefinition{
		Name: "ConnectorInternal",
		ID:   rand.NewServerID(),
	}

	s := server.NewRPCServer(sd, bus, opts...)

	sd.RegisterMethod("DialWhatsAppCall", false, false, true, true)
	sd.RegisterMethod("AcceptWhatsAppCall", false, false, true, true)
	sd.RegisterMethod("ConnectTwilioCall", false, false, true, true)
	return &connectorInternalServer{
		svc: svc,
		rpc: s,
	}, nil
}

func (s *connectorInternalServer) RegisterDialWhatsAppCallTopic(topic string) error {
	return server.RegisterHandler(s.rpc, "DialWhatsAppCall", []string{topic}, s.svc.DialWhatsAppCall, nil)
}

func (s *connectorInternalServer) DeregisterDialWhatsAppCallTopic(topic string) {
	s.rpc.DeregisterHandler("DialWhatsAppCall", []string{topic})
}

func (s *connectorInternalServer) RegisterAcceptWhatsAppCallTopic(topic string) error {
	return server.RegisterHandler(s.rpc, "AcceptWhatsAppCall", []string{topic}, s.svc.AcceptWhatsAppCall, nil)
}

func (s *connectorInternalServer) DeregisterAcceptWhatsAppCallTopic(topic string) {
	s.rpc.DeregisterHandler("AcceptWhatsAppCall", []string{topic})
}

func (s *connectorInternalServer) RegisterConnectTwilioCallTopic(topic string) error {
	return server.RegisterHandler(s.rpc, "ConnectTwilioCall", []string{topic}, s.svc.ConnectTwilioCall, nil)
}

func (s *connectorInternalServer) DeregisterConnectTwilioCallTopic(topic string) {
	s.rpc.DeregisterHandler("ConnectTwilioCall", []string{topic})
}

func (s *connectorInternalServer) Shutdown() {
	s.rpc.Close(false)
}

func (s *connectorInternalServer) Kill() {
	s.rpc.Close(true)
}

// ======================================
// ConnectorInternal Unimplemented Server
// ======================================

type UnimplementedConnectorInternalServer struct{}

func (UnimplementedConnectorInternalServer) DialWhatsAppCall(context.Context, *InternalDialWhatsAppCallRequest) (*livekit10.DialWhatsAppCallResponse, error) {
	return nil, psrpc.ErrUnimplemented
}

func (UnimplementedConnectorInternalServer) AcceptWhatsAppCall(context.Context, *InternalAcceptWhatsAppCallRequest) (*livekit10.AcceptWhatsAppCallResponse, error) {
	return nil, psrpc.ErrUnimplemented
}

func (UnimplementedConnectorInternalServer) ConnectTwilioCall(context.Context, *InternalConnectTwilioCallRequest) (*livekit11.ConnectTwilioCallResponse, error) {
	return nil, psrpc.ErrUnimplemented
}

// =================================
// ConnectorHandler Client Interface
// =================================

type ConnectorHandlerClient interface {
	ConnectWhatsAppCall(ctx context.Context, whatsappCallId string, req *livekit10.ConnectWhatsAppCallRequest, opts ...psrpc.RequestOption) (*livekit10.ConnectWhatsAppCallResponse, error)

	DisconnectWhatsAppCall(ctx context.Context, whatsappCallId string, req *livekit10.DisconnectWhatsAppCallRequest, opts ...psrpc.RequestOption) (*livekit10.DisconnectWhatsAppCallResponse, error)

	// Close immediately, without waiting for pending RPCs
	Close()
}

// =====================================
// ConnectorHandler ServerImpl Interface
// =====================================

type ConnectorHandlerServerImpl interface {
	ConnectWhatsAppCall(context.Context, *livekit10.ConnectWhatsAppCallRequest) (*livekit10.ConnectWhatsAppCallResponse, error)

	DisconnectWhatsAppCall(context.Context, *livekit10.DisconnectWhatsAppCallRequest) (*livekit10.DisconnectWhatsAppCallResponse, error)
}

// =================================
// ConnectorHandler Server Interface
// =================================

type ConnectorHandlerServer interface {
	RegisterConnectWhatsAppCallTopic(whatsappCallId string) error
	DeregisterConnectWhatsAppCallTopic(whatsappCallId string)
	RegisterDisconnectWhatsAppCallTopic(whatsappCallId string) error
	DeregisterDisconnectWhatsAppCallTopic(whatsappCallId string)

	// Close and wait for pending RPCs to complete
	Shutdown()

	// Close immediately, without waiting for pending RPCs
	Kill()
}

// =======================
// ConnectorHandler Client
// =======================

type connectorHandlerClient struct {
	client *client.RPCClient
}

// NewConnectorHandlerClient creates a psrpc client that implements the ConnectorHandlerClient interface.
func NewConnectorHandlerClient(bus psrpc.MessageBus, opts ...psrpc.ClientOption) (ConnectorHandlerClient, error) {
	sd := &info.ServiceDefinition{
		Name: "ConnectorHandler",
		ID:   rand.NewClientID(),
	}

	sd.RegisterMethod("ConnectWhatsAppCall", false, false, true, true)
	sd.RegisterMethod("DisconnectWhatsAppCall", false, false, true, true)

	rpcClient, err := client.NewRPCClient(sd, bus, opts...)
	if err != nil {
		return nil, err
	}

	return &connectorHandlerClient{
		client: rpcClient,
	}, nil
}

func (c *connectorHandlerClient) ConnectWhatsAppCall(ctx context.Context, whatsappCallId string, req *livekit10.ConnectWhatsAppCallRequest, opts ...psrpc.RequestOption) (*livekit10.ConnectWhatsAppCallResponse, error) {
	return client.RequestSingle[*livekit10.ConnectWhatsAppCallResponse](ctx, c.client, "ConnectWhatsAppCall", []string{whatsappCallId}, req, opts...)
}

func (c *connectorHandlerClient) DisconnectWhatsAppCall(ctx context.Context, whatsappCallId string, req *livekit10.DisconnectWhatsAppCallRequest, opts ...psrpc.RequestOption) (*livekit10.DisconnectWhatsAppCallResponse, error) {
	return client.RequestSingle[*livekit10.DisconnectWhatsAppCallResponse](ctx, c.client, "DisconnectWhatsAppCall", []string{whatsappCallId}, req, opts...)
}

func (s *connectorHandlerClient) Close() {
	s.client.Close()
}

// =======================
// ConnectorHandler Server
// =======================

type connectorHandlerServer struct {
	svc ConnectorHandlerServerImpl
	rpc *server.RPCServer
}

// NewConnectorHandlerServer builds a RPCServer that will route requests
// to the corresponding method in the provided svc implementation.
func NewConnectorHandlerServer(svc ConnectorHandlerServerImpl, bus psrpc.MessageBus, opts ...psrpc.ServerOption) (ConnectorHandlerServer, error) {
	sd := &info.ServiceDefinition{
		Name: "ConnectorHandler",
		ID:   rand.NewServerID(),
	}

	s := server.NewRPCServer(sd, bus, opts...)

	sd.RegisterMethod("ConnectWhatsAppCall", false, false, true, true)
	sd.RegisterMethod("DisconnectWhatsAppCall", false, false, true, true)
	return &connectorHandlerServer{
		svc: svc,
		rpc: s,
	}, nil
}

func (s *connectorHandlerServer) RegisterConnectWhatsAppCallTopic(whatsappCallId string) error {
	return server.RegisterHandler(s.rpc, "ConnectWhatsAppCall", []string{whatsappCallId}, s.svc.ConnectWhatsAppCall, nil)
}

func (s *connectorHandlerServer) DeregisterConnectWhatsAppCallTopic(whatsappCallId string) {
	s.rpc.DeregisterHandler("ConnectWhatsAppCall", []string{whatsappCallId})
}

func (s *connectorHandlerServer) RegisterDisconnectWhatsAppCallTopic(whatsappCallId string) error {
	return server.RegisterHandler(s.rpc, "DisconnectWhatsAppCall", []string{whatsappCallId}, s.svc.DisconnectWhatsAppCall, nil)
}

func (s *connectorHandlerServer) DeregisterDisconnectWhatsAppCallTopic(whatsappCallId string) {
	s.rpc.DeregisterHandler("DisconnectWhatsAppCall", []string{whatsappCallId})
}

func (s *connectorHandlerServer) Shutdown() {
	s.rpc.Close(false)
}

func (s *connectorHandlerServer) Kill() {
	s.rpc.Close(true)
}

// =====================================
// ConnectorHandler Unimplemented Server
// =====================================

type UnimplementedConnectorHandlerServer struct{}

func (UnimplementedConnectorHandlerServer) ConnectWhatsAppCall(context.Context, *livekit10.ConnectWhatsAppCallRequest) (*livekit10.ConnectWhatsAppCallResponse, error) {
	return nil, psrpc.ErrUnimplemented
}

func (UnimplementedConnectorHandlerServer) DisconnectWhatsAppCall(context.Context, *livekit10.DisconnectWhatsAppCallRequest) (*livekit10.DisconnectWhatsAppCallResponse, error) {
	return nil, psrpc.ErrUnimplemented
}

var psrpcFileDescriptor12 = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0xe5, 0x20, 0x0d, 0xc9, 0xfc, 0x51, 0xf0, 0xa4, 0x69, 0xe4, 0x00, 0x69, 0x36, 0x36,
	0x38, 0x2c, 0x91, 0xca, 0x0d, 0x90, 0xd0, 0xe8, 0x0e, 0x8c, 0x63, 0x84, 0x84, 0xc4, 0x25, 0xca,
	0x3c, 0x97, 0x1a, 0x1c, 0xbf, 0xc6, 0x71, 0xa9, 0x84, 0xb8, 0x72, 0xe8, 0x37, 0xe0, 0x84, 0x10,
	0x1f, 0xa1, 0x5f, 0x83, 0x2f, 0x85, 0x48, 0xe2, 0xd0, 0xa4, 0x49, 0x7a, 0xe9, 0x2d, 0x76, 0x9e,
	0xf7, 0x7d, 0x7e, 0x7e, 0x1f, 0x27, 0x78, 0x5f, 0x2b, 0x1a, 0x51, 0x90, 0x92, 0x51, 0x03, 0x3a,
	0x54, 0x1a, 0x0c, 0x90, 0x1b, 0x5a, 0x51, 0xef, 0x0e, 0x28, 0xc3, 0x41, 0xe6, 0xe5, 0x9e, 0xe7,
	0x0b, 0xfe, 0x85, 0x7d, 0xe2, 0x26, 0xa9, 0xc5, 0xc9, 0x62, 0x96, 0x9a, 0x3c, 0x55, 0xaa, 0x52,
	0x3c, 0xd8, 0x54, 0x98, 0x05, 0x17, 0x1c, 0xaa, 0xf7, 0x6e, 0x69, 0x95, 0x65, 0x20, 0xcb, 0x9d,
	0xe0, 0x27, 0xc2, 0x0f, 0x2f, 0xa5, 0x61, 0x5a, 0xa6, 0xe2, 0x82, 0xa7, 0xe2, 0xdd, 0xbf, 0x86,
	0xe7, 0x4a, 0x4d, 0x52, 0x21, 0x62, 0xf6, 0x79, 0xce, 0x72, 0x43, 0x9e, 0xe1, 0x9b, 0xba, 0x7c,
	0x3c, 0x44, 0x3e, 0x7a, 0x7c, 0x6b, 0xec, 0x87, 0x95, 0x4f, 0xd8, 0x53, 0x12, 0xdb, 0x02, 0xf2,
	0x12, 0xdf, 0xd5, 0x00, 0x59, 0xf2, 0x11, 0xb8, 0x4c, 0xb8, 0x9c, 0xc2, 0xa1, 0x53, 0xb4, 0xb8,
	0x1f, 0x6a, 0x45, 0x43, 0xeb, 0x1c, 0x03, 0x64, 0x6f, 0x80, 0xcb, 0x4b, 0x39, 0x85, 0xf8, 0xb6,
	0x5e, 0x5b, 0x05, 0xbf, 0x11, 0x1e, 0x59, 0xd9, 0x39, 0xa5, 0x4c, 0x99, 0x2e, 0xc4, 0x17, 0x6d,
	0xc4, 0xa0, 0x46, 0xec, 0x2d, 0xda, 0x21, 0xe4, 0x2f, 0x84, 0x7d, 0x2b, 0x9b, 0x94, 0xa3, 0x7f,
	0x5b, 0xcc, 0x7d, 0x9d, 0xf1, 0x79, 0x9b, 0x71, 0x54, 0x33, 0xf6, 0xd5, 0xec, 0x0e, 0x71, 0xfc,
	0xc7, 0xc1, 0xf7, 0x26, 0xf6, 0x56, 0x58, 0x3d, 0xa1, 0xd8, 0x6d, 0x47, 0x48, 0x8e, 0x1b, 0x2d,
	0x7b, 0x12, 0xf6, 0x46, 0x03, 0x77, 0x20, 0x57, 0x20, 0x73, 0x16, 0xec, 0xad, 0x96, 0xc8, 0x71,
	0x11, 0xe1, 0x98, 0x6c, 0x86, 0x40, 0x4e, 0x1a, 0x36, 0xbd, 0x29, 0x79, 0x47, 0x83, 0x49, 0xb6,
	0xac, 0xa6, 0xf5, 0x21, 0xff, 0xcf, 0x92, 0x3c, 0x6a, 0x38, 0xf5, 0xcd, 0xda, 0x0b, 0x86, 0xe2,
	0x68, 0xfa, 0x8c, 0x7f, 0x38, 0xd8, 0xad, 0xa7, 0xf9, 0x3a, 0x95, 0xd7, 0x82, 0x69, 0xf2, 0x0d,
	0xef, 0x57, 0x7b, 0x8d, 0x83, 0x1e, 0xb5, 0xfb, 0x76, 0x9d, 0xf2, 0x78, 0x58, 0x54, 0xd9, 0x7b,
	0xab, 0x25, 0x3a, 0x70, 0x91, 0x47, 0x88, 0x6b, 0xbf, 0xfc, 0x84, 0xa6, 0x42, 0x24, 0xfc, 0x9a,
	0x7c, 0x47, 0xf8, 0xe0, 0x82, 0xe7, 0xb4, 0x83, 0xe0, 0x64, 0x2d, 0xab, 0x2e, 0x81, 0x85, 0x38,
	0xdd, 0xaa, 0xdb, 0xce, 0xf1, 0xea, 0xc9, 0xfb, 0xd3, 0x0f, 0xdc, 0xcc, 0xe6, 0x57, 0x21, 0x85,
	0x2c, 0xd2, 0xec, 0x2b, 0x3f, 0xe3, 0x10, 0x55, 0x8d, 0xcf, 0x8a, 0xbf, 0x0e, 0x05, 0x11, 0x69,
	0x45, 0xaf, 0xf6, 0x8a, 0xd5, 0xd3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x22, 0x7e, 0xa4, 0x05,
	0x02, 0x05, 0x00, 0x00,
}
