// Code generated by protoc-gen-psrpc v0.7.0, DO NOT EDIT.
// source: rpc/egress.proto

package rpc

import (
	"context"

	"github.com/livekit/psrpc"
	"github.com/livekit/psrpc/pkg/client"
	"github.com/livekit/psrpc/pkg/info"
	"github.com/livekit/psrpc/pkg/rand"
	"github.com/livekit/psrpc/pkg/server"
	"github.com/livekit/psrpc/version"
)
import livekit4 "github.com/rezi-io/livekit-protocol/livekit"

var _ = version.PsrpcVersion_0_7

// ===============================
// EgressInternal Client Interface
// ===============================

type EgressInternalClient interface {
	StartEgress(ctx context.Context, topic string, req *StartEgressRequest, opts ...psrpc.RequestOption) (*livekit4.EgressInfo, error)

	ListActiveEgress(ctx context.Context, topic string, req *ListActiveEgressRequest, opts ...psrpc.RequestOption) (<-chan *psrpc.Response[*ListActiveEgressResponse], error)

	// Close immediately, without waiting for pending RPCs
	Close()
}

// ===================================
// EgressInternal ServerImpl Interface
// ===================================

type EgressInternalServerImpl interface {
	StartEgress(context.Context, *StartEgressRequest) (*livekit4.EgressInfo, error)
	StartEgressAffinity(context.Context, *StartEgressRequest) float32

	ListActiveEgress(context.Context, *ListActiveEgressRequest) (*ListActiveEgressResponse, error)
}

// ===============================
// EgressInternal Server Interface
// ===============================

type EgressInternalServer interface {
	RegisterStartEgressTopic(topic string) error
	DeregisterStartEgressTopic(topic string)
	RegisterListActiveEgressTopic(topic string) error
	DeregisterListActiveEgressTopic(topic string)

	// Close and wait for pending RPCs to complete
	Shutdown()

	// Close immediately, without waiting for pending RPCs
	Kill()
}

// =====================
// EgressInternal Client
// =====================

type egressInternalClient struct {
	client *client.RPCClient
}

// NewEgressInternalClient creates a psrpc client that implements the EgressInternalClient interface.
func NewEgressInternalClient(bus psrpc.MessageBus, opts ...psrpc.ClientOption) (EgressInternalClient, error) {
	sd := &info.ServiceDefinition{
		Name: "EgressInternal",
		ID:   rand.NewClientID(),
	}

	sd.RegisterMethod("StartEgress", true, false, true, false)
	sd.RegisterMethod("ListActiveEgress", false, true, false, false)

	rpcClient, err := client.NewRPCClient(sd, bus, opts...)
	if err != nil {
		return nil, err
	}

	return &egressInternalClient{
		client: rpcClient,
	}, nil
}

func (c *egressInternalClient) StartEgress(ctx context.Context, topic string, req *StartEgressRequest, opts ...psrpc.RequestOption) (*livekit4.EgressInfo, error) {
	return client.RequestSingle[*livekit4.EgressInfo](ctx, c.client, "StartEgress", []string{topic}, req, opts...)
}

func (c *egressInternalClient) ListActiveEgress(ctx context.Context, topic string, req *ListActiveEgressRequest, opts ...psrpc.RequestOption) (<-chan *psrpc.Response[*ListActiveEgressResponse], error) {
	return client.RequestMulti[*ListActiveEgressResponse](ctx, c.client, "ListActiveEgress", []string{topic}, req, opts...)
}

func (s *egressInternalClient) Close() {
	s.client.Close()
}

// =====================
// EgressInternal Server
// =====================

type egressInternalServer struct {
	svc EgressInternalServerImpl
	rpc *server.RPCServer
}

// NewEgressInternalServer builds a RPCServer that will route requests
// to the corresponding method in the provided svc implementation.
func NewEgressInternalServer(svc EgressInternalServerImpl, bus psrpc.MessageBus, opts ...psrpc.ServerOption) (EgressInternalServer, error) {
	sd := &info.ServiceDefinition{
		Name: "EgressInternal",
		ID:   rand.NewServerID(),
	}

	s := server.NewRPCServer(sd, bus, opts...)

	sd.RegisterMethod("StartEgress", true, false, true, false)
	sd.RegisterMethod("ListActiveEgress", false, true, false, false)
	return &egressInternalServer{
		svc: svc,
		rpc: s,
	}, nil
}

func (s *egressInternalServer) RegisterStartEgressTopic(topic string) error {
	return server.RegisterHandler(s.rpc, "StartEgress", []string{topic}, s.svc.StartEgress, s.svc.StartEgressAffinity)
}

func (s *egressInternalServer) DeregisterStartEgressTopic(topic string) {
	s.rpc.DeregisterHandler("StartEgress", []string{topic})
}

func (s *egressInternalServer) RegisterListActiveEgressTopic(topic string) error {
	return server.RegisterHandler(s.rpc, "ListActiveEgress", []string{topic}, s.svc.ListActiveEgress, nil)
}

func (s *egressInternalServer) DeregisterListActiveEgressTopic(topic string) {
	s.rpc.DeregisterHandler("ListActiveEgress", []string{topic})
}

func (s *egressInternalServer) Shutdown() {
	s.rpc.Close(false)
}

func (s *egressInternalServer) Kill() {
	s.rpc.Close(true)
}

// ===================================
// EgressInternal Unimplemented Server
// ===================================

type UnimplementedEgressInternalServer struct{}

func (UnimplementedEgressInternalServer) StartEgress(context.Context, *StartEgressRequest) (*livekit4.EgressInfo, error) {
	return nil, psrpc.ErrUnimplemented
}
func (UnimplementedEgressInternalServer) StartEgressAffinity(context.Context, *StartEgressRequest) float32 {
	return -1
}

func (UnimplementedEgressInternalServer) ListActiveEgress(context.Context, *ListActiveEgressRequest) (*ListActiveEgressResponse, error) {
	return nil, psrpc.ErrUnimplemented
}

// ==============================
// EgressHandler Client Interface
// ==============================

type EgressHandlerClient interface {
	UpdateStream(ctx context.Context, topic string, req *livekit4.UpdateStreamRequest, opts ...psrpc.RequestOption) (*livekit4.EgressInfo, error)

	StopEgress(ctx context.Context, topic string, req *livekit4.StopEgressRequest, opts ...psrpc.RequestOption) (*livekit4.EgressInfo, error)

	// Close immediately, without waiting for pending RPCs
	Close()
}

// ==================================
// EgressHandler ServerImpl Interface
// ==================================

type EgressHandlerServerImpl interface {
	UpdateStream(context.Context, *livekit4.UpdateStreamRequest) (*livekit4.EgressInfo, error)

	StopEgress(context.Context, *livekit4.StopEgressRequest) (*livekit4.EgressInfo, error)
}

// ==============================
// EgressHandler Server Interface
// ==============================

type EgressHandlerServer interface {
	RegisterUpdateStreamTopic(topic string) error
	DeregisterUpdateStreamTopic(topic string)
	RegisterStopEgressTopic(topic string) error
	DeregisterStopEgressTopic(topic string)

	// Close and wait for pending RPCs to complete
	Shutdown()

	// Close immediately, without waiting for pending RPCs
	Kill()
}

// ====================
// EgressHandler Client
// ====================

type egressHandlerClient struct {
	client *client.RPCClient
}

// NewEgressHandlerClient creates a psrpc client that implements the EgressHandlerClient interface.
func NewEgressHandlerClient(bus psrpc.MessageBus, opts ...psrpc.ClientOption) (EgressHandlerClient, error) {
	sd := &info.ServiceDefinition{
		Name: "EgressHandler",
		ID:   rand.NewClientID(),
	}

	sd.RegisterMethod("UpdateStream", false, false, true, true)
	sd.RegisterMethod("StopEgress", false, false, true, true)

	rpcClient, err := client.NewRPCClient(sd, bus, opts...)
	if err != nil {
		return nil, err
	}

	return &egressHandlerClient{
		client: rpcClient,
	}, nil
}

func (c *egressHandlerClient) UpdateStream(ctx context.Context, topic string, req *livekit4.UpdateStreamRequest, opts ...psrpc.RequestOption) (*livekit4.EgressInfo, error) {
	return client.RequestSingle[*livekit4.EgressInfo](ctx, c.client, "UpdateStream", []string{topic}, req, opts...)
}

func (c *egressHandlerClient) StopEgress(ctx context.Context, topic string, req *livekit4.StopEgressRequest, opts ...psrpc.RequestOption) (*livekit4.EgressInfo, error) {
	return client.RequestSingle[*livekit4.EgressInfo](ctx, c.client, "StopEgress", []string{topic}, req, opts...)
}

func (s *egressHandlerClient) Close() {
	s.client.Close()
}

// ====================
// EgressHandler Server
// ====================

type egressHandlerServer struct {
	svc EgressHandlerServerImpl
	rpc *server.RPCServer
}

// NewEgressHandlerServer builds a RPCServer that will route requests
// to the corresponding method in the provided svc implementation.
func NewEgressHandlerServer(svc EgressHandlerServerImpl, bus psrpc.MessageBus, opts ...psrpc.ServerOption) (EgressHandlerServer, error) {
	sd := &info.ServiceDefinition{
		Name: "EgressHandler",
		ID:   rand.NewServerID(),
	}

	s := server.NewRPCServer(sd, bus, opts...)

	sd.RegisterMethod("UpdateStream", false, false, true, true)
	sd.RegisterMethod("StopEgress", false, false, true, true)
	return &egressHandlerServer{
		svc: svc,
		rpc: s,
	}, nil
}

func (s *egressHandlerServer) RegisterUpdateStreamTopic(topic string) error {
	return server.RegisterHandler(s.rpc, "UpdateStream", []string{topic}, s.svc.UpdateStream, nil)
}

func (s *egressHandlerServer) DeregisterUpdateStreamTopic(topic string) {
	s.rpc.DeregisterHandler("UpdateStream", []string{topic})
}

func (s *egressHandlerServer) RegisterStopEgressTopic(topic string) error {
	return server.RegisterHandler(s.rpc, "StopEgress", []string{topic}, s.svc.StopEgress, nil)
}

func (s *egressHandlerServer) DeregisterStopEgressTopic(topic string) {
	s.rpc.DeregisterHandler("StopEgress", []string{topic})
}

func (s *egressHandlerServer) Shutdown() {
	s.rpc.Close(false)
}

func (s *egressHandlerServer) Kill() {
	s.rpc.Close(true)
}

// ==================================
// EgressHandler Unimplemented Server
// ==================================

type UnimplementedEgressHandlerServer struct{}

func (UnimplementedEgressHandlerServer) UpdateStream(context.Context, *livekit4.UpdateStreamRequest) (*livekit4.EgressInfo, error) {
	return nil, psrpc.ErrUnimplemented
}

func (UnimplementedEgressHandlerServer) StopEgress(context.Context, *livekit4.StopEgressRequest) (*livekit4.EgressInfo, error) {
	return nil, psrpc.ErrUnimplemented
}

var psrpcFileDescriptor2 = []byte{
	// 566 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xf1, 0xba, 0x76, 0xeb, 0xeb, 0x5a, 0x2a, 0x33, 0x34, 0x2f, 0xdb, 0xa4, 0xd2, 0x21,
	0x11, 0x0e, 0x4b, 0xa7, 0xed, 0xc4, 0x0d, 0x3a, 0x55, 0xac, 0xd2, 0x24, 0x50, 0xc6, 0x84, 0x04,
	0x87, 0x28, 0x71, 0x4c, 0xb1, 0x9a, 0xc4, 0xc6, 0x76, 0x36, 0x89, 0x4f, 0xc0, 0x3e, 0x06, 0x47,
	0xae, 0x93, 0xe0, 0xf3, 0xa1, 0x3a, 0x5d, 0x96, 0x76, 0x1a, 0xe2, 0xe8, 0xff, 0xff, 0xfd, 0x7f,
	0x79, 0xef, 0xe9, 0x29, 0xd0, 0x55, 0x92, 0x0e, 0xd8, 0x44, 0x31, 0xad, 0x3d, 0xa9, 0x84, 0x11,
	0xb8, 0xa6, 0x24, 0x75, 0xda, 0x42, 0x1a, 0x2e, 0xb2, 0xb9, 0xe6, 0x6c, 0x26, 0x62, 0x32, 0x61,
	0x6a, 0xb0, 0xac, 0xf2, 0x4b, 0x36, 0xe5, 0x26, 0xa8, 0xe6, 0xfb, 0xbf, 0x56, 0x01, 0x9f, 0x9b,
	0x50, 0x99, 0x91, 0x55, 0x7d, 0xf6, 0x2d, 0x67, 0xda, 0xe0, 0x1d, 0x68, 0x16, 0x65, 0x01, 0x8f,
	0x09, 0xea, 0x21, 0xb7, 0xe9, 0xaf, 0x17, 0xc2, 0x38, 0xc6, 0x67, 0xd0, 0x51, 0x42, 0xa4, 0x01,
	0x15, 0xa9, 0x14, 0x9a, 0x1b, 0x46, 0xea, 0x3d, 0xe4, 0xb6, 0x8e, 0xf6, 0xbd, 0xf9, 0x27, 0x3c,
	0x5f, 0x88, 0xf4, 0xe4, 0xd6, 0x5d, 0x20, 0x9f, 0x3e, 0xf2, 0xdb, 0xaa, 0xea, 0xe2, 0x03, 0xa8,
	0x5d, 0xb1, 0x88, 0xb4, 0x2c, 0x62, 0xbb, 0x44, 0x7c, 0x64, 0xd1, 0x72, 0x70, 0x56, 0x87, 0x47,
	0xd0, 0x92, 0xa1, 0x32, 0x9c, 0x72, 0x19, 0x66, 0x86, 0xb4, 0x6d, 0xec, 0x59, 0x19, 0x7b, 0x7f,
	0xe7, 0x2d, 0xc7, 0xab, 0x39, 0xfc, 0x0e, 0x1e, 0x1b, 0x15, 0xd2, 0x69, 0x65, 0x88, 0x86, 0x45,
	0x3d, 0x2f, 0x51, 0x1f, 0x66, 0xfe, 0x83, 0x53, 0x74, 0xcc, 0x82, 0x8d, 0x8f, 0xa1, 0x6e, 0x15,
	0xb2, 0x66, 0x31, 0x3b, 0x8b, 0x98, 0xe5, 0x74, 0x51, 0x8b, 0xb7, 0x60, 0xcd, 0x6e, 0x92, 0xc7,
	0xa4, 0x66, 0x97, 0xdc, 0x98, 0x3d, 0xc7, 0x31, 0x76, 0xa0, 0x6e, 0xc4, 0x94, 0x65, 0x64, 0x7d,
	0x26, 0x0f, 0x57, 0x7f, 0xfc, 0x26, 0xc8, 0x2f, 0x24, 0xfc, 0x14, 0x1a, 0x57, 0x3a, 0xc8, 0x55,
	0x42, 0x9a, 0x36, 0x53, 0xbf, 0xd2, 0x17, 0x2a, 0xc1, 0x87, 0xb0, 0x49, 0x13, 0x91, 0xc7, 0x41,
	0x14, 0xd2, 0x69, 0x2e, 0x03, 0x96, 0x85, 0x51, 0xc2, 0x62, 0x02, 0x3d, 0xe4, 0xae, 0xfb, 0xd8,
	0x7a, 0x43, 0x6b, 0x8d, 0x0a, 0x07, 0xef, 0x43, 0x9b, 0x69, 0xc3, 0xd3, 0xd0, 0xb0, 0x38, 0xa0,
	0x32, 0x27, 0x9d, 0x1e, 0x72, 0x91, 0xbf, 0x51, 0x8a, 0x27, 0x32, 0x1f, 0x36, 0x61, 0x4d, 0x15,
	0x6d, 0xf7, 0xb7, 0x61, 0xeb, 0x8c, 0x6b, 0xf3, 0x86, 0x1a, 0x7e, 0xb9, 0xb8, 0x8f, 0xfe, 0x2b,
	0x20, 0xf7, 0x2d, 0x2d, 0x45, 0xa6, 0x19, 0xde, 0x03, 0x28, 0x6f, 0x49, 0x13, 0xd4, 0xab, 0xb9,
	0x4d, 0xbf, 0x79, 0x7b, 0x4c, 0xfa, 0xe8, 0x0f, 0x82, 0x4e, 0x91, 0x18, 0x67, 0x86, 0xa9, 0x2c,
	0x4c, 0xf0, 0x5b, 0x68, 0x55, 0x6e, 0x12, 0x6f, 0x79, 0x4a, 0x52, 0xef, 0xfe, 0x95, 0x3a, 0x4f,
	0xca, 0x25, 0xdf, 0x02, 0xbe, 0x88, 0x3e, 0xdc, 0x5c, 0xa3, 0x46, 0x17, 0xbd, 0x46, 0x87, 0x08,
	0x7f, 0x86, 0xee, 0x72, 0x5b, 0x78, 0xd7, 0xd2, 0x1e, 0x18, 0xc4, 0xd9, 0x7b, 0xc0, 0x2d, 0x66,
	0x29, 0xe1, 0x2b, 0x2e, 0x3a, 0xfa, 0x89, 0xa0, 0x5d, 0xd8, 0xa7, 0x61, 0x16, 0x27, 0x4c, 0xe1,
	0x31, 0x6c, 0x5c, 0xc8, 0x38, 0x34, 0xec, 0xdc, 0x28, 0x16, 0xa6, 0x78, 0xb7, 0xec, 0xaf, 0x2a,
	0xff, 0xb3, 0xfb, 0xc6, 0xcd, 0x35, 0x5a, 0xe9, 0x22, 0x3c, 0x02, 0x38, 0x37, 0x42, 0xce, 0x7b,
	0x76, 0xca, 0xd2, 0x3b, 0xf1, 0x7f, 0x30, 0xc3, 0x97, 0x9f, 0x5e, 0x4c, 0xb8, 0xf9, 0x9a, 0x47,
	0x1e, 0x15, 0xe9, 0x40, 0xb1, 0xef, 0xfc, 0x80, 0x8b, 0xc1, 0x3c, 0x70, 0x60, 0x7f, 0x01, 0x54,
	0x24, 0x03, 0x25, 0x69, 0xd4, 0xb0, 0xaf, 0xe3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x05, 0x37,
	0xd7, 0x14, 0x64, 0x04, 0x00, 0x00,
}
