// Code generated by protoc-gen-psrpc v0.7.0, DO NOT EDIT.
// source: rpc/participant.proto

package rpc

import (
	"context"

	"github.com/livekit/psrpc"
	"github.com/livekit/psrpc/pkg/client"
	"github.com/livekit/psrpc/pkg/info"
	"github.com/livekit/psrpc/pkg/rand"
	"github.com/livekit/psrpc/pkg/server"
	"github.com/livekit/psrpc/version"
)
import livekit1 "github.com/rezi-io/livekit-protocol/livekit"
import livekit6 "github.com/rezi-io/livekit-protocol/livekit"

var _ = version.PsrpcVersion_0_7

// ============================
// Participant Client Interface
// ============================

type ParticipantClient[ParticipantTopicType ~string] interface {
	RemoveParticipant(ctx context.Context, participant ParticipantTopicType, req *livekit6.RoomParticipantIdentity, opts ...psrpc.RequestOption) (*livekit6.RemoveParticipantResponse, error)

	MutePublishedTrack(ctx context.Context, participant ParticipantTopicType, req *livekit6.MuteRoomTrackRequest, opts ...psrpc.RequestOption) (*livekit6.MuteRoomTrackResponse, error)

	UpdateParticipant(ctx context.Context, participant ParticipantTopicType, req *livekit6.UpdateParticipantRequest, opts ...psrpc.RequestOption) (*livekit1.ParticipantInfo, error)

	UpdateSubscriptions(ctx context.Context, participant ParticipantTopicType, req *livekit6.UpdateSubscriptionsRequest, opts ...psrpc.RequestOption) (*livekit6.UpdateSubscriptionsResponse, error)

	ForwardParticipant(ctx context.Context, participant ParticipantTopicType, req *livekit6.ForwardParticipantRequest, opts ...psrpc.RequestOption) (*livekit6.ForwardParticipantResponse, error)

	MoveParticipant(ctx context.Context, participant ParticipantTopicType, req *livekit6.MoveParticipantRequest, opts ...psrpc.RequestOption) (*livekit6.MoveParticipantResponse, error)

	PerformRpc(ctx context.Context, participant ParticipantTopicType, req *livekit6.PerformRpcRequest, opts ...psrpc.RequestOption) (*livekit6.PerformRpcResponse, error)

	// Close immediately, without waiting for pending RPCs
	Close()
}

// ================================
// Participant ServerImpl Interface
// ================================

type ParticipantServerImpl interface {
	RemoveParticipant(context.Context, *livekit6.RoomParticipantIdentity) (*livekit6.RemoveParticipantResponse, error)

	MutePublishedTrack(context.Context, *livekit6.MuteRoomTrackRequest) (*livekit6.MuteRoomTrackResponse, error)

	UpdateParticipant(context.Context, *livekit6.UpdateParticipantRequest) (*livekit1.ParticipantInfo, error)

	UpdateSubscriptions(context.Context, *livekit6.UpdateSubscriptionsRequest) (*livekit6.UpdateSubscriptionsResponse, error)

	ForwardParticipant(context.Context, *livekit6.ForwardParticipantRequest) (*livekit6.ForwardParticipantResponse, error)

	MoveParticipant(context.Context, *livekit6.MoveParticipantRequest) (*livekit6.MoveParticipantResponse, error)

	PerformRpc(context.Context, *livekit6.PerformRpcRequest) (*livekit6.PerformRpcResponse, error)
}

// ============================
// Participant Server Interface
// ============================

type ParticipantServer[ParticipantTopicType ~string] interface {
	RegisterRemoveParticipantTopic(participant ParticipantTopicType) error
	DeregisterRemoveParticipantTopic(participant ParticipantTopicType)
	RegisterMutePublishedTrackTopic(participant ParticipantTopicType) error
	DeregisterMutePublishedTrackTopic(participant ParticipantTopicType)
	RegisterUpdateParticipantTopic(participant ParticipantTopicType) error
	DeregisterUpdateParticipantTopic(participant ParticipantTopicType)
	RegisterUpdateSubscriptionsTopic(participant ParticipantTopicType) error
	DeregisterUpdateSubscriptionsTopic(participant ParticipantTopicType)
	RegisterForwardParticipantTopic(participant ParticipantTopicType) error
	DeregisterForwardParticipantTopic(participant ParticipantTopicType)
	RegisterMoveParticipantTopic(participant ParticipantTopicType) error
	DeregisterMoveParticipantTopic(participant ParticipantTopicType)
	RegisterPerformRpcTopic(participant ParticipantTopicType) error
	DeregisterPerformRpcTopic(participant ParticipantTopicType)
	RegisterAllParticipantTopics(participant ParticipantTopicType) error
	DeregisterAllParticipantTopics(participant ParticipantTopicType)

	// Close and wait for pending RPCs to complete
	Shutdown()

	// Close immediately, without waiting for pending RPCs
	Kill()
}

// ==================
// Participant Client
// ==================

type participantClient[ParticipantTopicType ~string] struct {
	client *client.RPCClient
}

// NewParticipantClient creates a psrpc client that implements the ParticipantClient interface.
func NewParticipantClient[ParticipantTopicType ~string](bus psrpc.MessageBus, opts ...psrpc.ClientOption) (ParticipantClient[ParticipantTopicType], error) {
	sd := &info.ServiceDefinition{
		Name: "Participant",
		ID:   rand.NewClientID(),
	}

	sd.RegisterMethod("RemoveParticipant", false, false, true, true)
	sd.RegisterMethod("MutePublishedTrack", false, false, true, true)
	sd.RegisterMethod("UpdateParticipant", false, false, true, true)
	sd.RegisterMethod("UpdateSubscriptions", false, false, true, true)
	sd.RegisterMethod("ForwardParticipant", false, false, true, true)
	sd.RegisterMethod("MoveParticipant", false, false, true, true)
	sd.RegisterMethod("PerformRpc", false, false, true, true)

	rpcClient, err := client.NewRPCClient(sd, bus, opts...)
	if err != nil {
		return nil, err
	}

	return &participantClient[ParticipantTopicType]{
		client: rpcClient,
	}, nil
}

func (c *participantClient[ParticipantTopicType]) RemoveParticipant(ctx context.Context, participant ParticipantTopicType, req *livekit6.RoomParticipantIdentity, opts ...psrpc.RequestOption) (*livekit6.RemoveParticipantResponse, error) {
	return client.RequestSingle[*livekit6.RemoveParticipantResponse](ctx, c.client, "RemoveParticipant", []string{string(participant)}, req, opts...)
}

func (c *participantClient[ParticipantTopicType]) MutePublishedTrack(ctx context.Context, participant ParticipantTopicType, req *livekit6.MuteRoomTrackRequest, opts ...psrpc.RequestOption) (*livekit6.MuteRoomTrackResponse, error) {
	return client.RequestSingle[*livekit6.MuteRoomTrackResponse](ctx, c.client, "MutePublishedTrack", []string{string(participant)}, req, opts...)
}

func (c *participantClient[ParticipantTopicType]) UpdateParticipant(ctx context.Context, participant ParticipantTopicType, req *livekit6.UpdateParticipantRequest, opts ...psrpc.RequestOption) (*livekit1.ParticipantInfo, error) {
	return client.RequestSingle[*livekit1.ParticipantInfo](ctx, c.client, "UpdateParticipant", []string{string(participant)}, req, opts...)
}

func (c *participantClient[ParticipantTopicType]) UpdateSubscriptions(ctx context.Context, participant ParticipantTopicType, req *livekit6.UpdateSubscriptionsRequest, opts ...psrpc.RequestOption) (*livekit6.UpdateSubscriptionsResponse, error) {
	return client.RequestSingle[*livekit6.UpdateSubscriptionsResponse](ctx, c.client, "UpdateSubscriptions", []string{string(participant)}, req, opts...)
}

func (c *participantClient[ParticipantTopicType]) ForwardParticipant(ctx context.Context, participant ParticipantTopicType, req *livekit6.ForwardParticipantRequest, opts ...psrpc.RequestOption) (*livekit6.ForwardParticipantResponse, error) {
	return client.RequestSingle[*livekit6.ForwardParticipantResponse](ctx, c.client, "ForwardParticipant", []string{string(participant)}, req, opts...)
}

func (c *participantClient[ParticipantTopicType]) MoveParticipant(ctx context.Context, participant ParticipantTopicType, req *livekit6.MoveParticipantRequest, opts ...psrpc.RequestOption) (*livekit6.MoveParticipantResponse, error) {
	return client.RequestSingle[*livekit6.MoveParticipantResponse](ctx, c.client, "MoveParticipant", []string{string(participant)}, req, opts...)
}

func (c *participantClient[ParticipantTopicType]) PerformRpc(ctx context.Context, participant ParticipantTopicType, req *livekit6.PerformRpcRequest, opts ...psrpc.RequestOption) (*livekit6.PerformRpcResponse, error) {
	return client.RequestSingle[*livekit6.PerformRpcResponse](ctx, c.client, "PerformRpc", []string{string(participant)}, req, opts...)
}

func (s *participantClient[ParticipantTopicType]) Close() {
	s.client.Close()
}

// ==================
// Participant Server
// ==================

type participantServer[ParticipantTopicType ~string] struct {
	svc ParticipantServerImpl
	rpc *server.RPCServer
}

// NewParticipantServer builds a RPCServer that will route requests
// to the corresponding method in the provided svc implementation.
func NewParticipantServer[ParticipantTopicType ~string](svc ParticipantServerImpl, bus psrpc.MessageBus, opts ...psrpc.ServerOption) (ParticipantServer[ParticipantTopicType], error) {
	sd := &info.ServiceDefinition{
		Name: "Participant",
		ID:   rand.NewServerID(),
	}

	s := server.NewRPCServer(sd, bus, opts...)

	sd.RegisterMethod("RemoveParticipant", false, false, true, true)
	sd.RegisterMethod("MutePublishedTrack", false, false, true, true)
	sd.RegisterMethod("UpdateParticipant", false, false, true, true)
	sd.RegisterMethod("UpdateSubscriptions", false, false, true, true)
	sd.RegisterMethod("ForwardParticipant", false, false, true, true)
	sd.RegisterMethod("MoveParticipant", false, false, true, true)
	sd.RegisterMethod("PerformRpc", false, false, true, true)
	return &participantServer[ParticipantTopicType]{
		svc: svc,
		rpc: s,
	}, nil
}

func (s *participantServer[ParticipantTopicType]) RegisterRemoveParticipantTopic(participant ParticipantTopicType) error {
	return server.RegisterHandler(s.rpc, "RemoveParticipant", []string{string(participant)}, s.svc.RemoveParticipant, nil)
}

func (s *participantServer[ParticipantTopicType]) DeregisterRemoveParticipantTopic(participant ParticipantTopicType) {
	s.rpc.DeregisterHandler("RemoveParticipant", []string{string(participant)})
}

func (s *participantServer[ParticipantTopicType]) RegisterMutePublishedTrackTopic(participant ParticipantTopicType) error {
	return server.RegisterHandler(s.rpc, "MutePublishedTrack", []string{string(participant)}, s.svc.MutePublishedTrack, nil)
}

func (s *participantServer[ParticipantTopicType]) DeregisterMutePublishedTrackTopic(participant ParticipantTopicType) {
	s.rpc.DeregisterHandler("MutePublishedTrack", []string{string(participant)})
}

func (s *participantServer[ParticipantTopicType]) RegisterUpdateParticipantTopic(participant ParticipantTopicType) error {
	return server.RegisterHandler(s.rpc, "UpdateParticipant", []string{string(participant)}, s.svc.UpdateParticipant, nil)
}

func (s *participantServer[ParticipantTopicType]) DeregisterUpdateParticipantTopic(participant ParticipantTopicType) {
	s.rpc.DeregisterHandler("UpdateParticipant", []string{string(participant)})
}

func (s *participantServer[ParticipantTopicType]) RegisterUpdateSubscriptionsTopic(participant ParticipantTopicType) error {
	return server.RegisterHandler(s.rpc, "UpdateSubscriptions", []string{string(participant)}, s.svc.UpdateSubscriptions, nil)
}

func (s *participantServer[ParticipantTopicType]) DeregisterUpdateSubscriptionsTopic(participant ParticipantTopicType) {
	s.rpc.DeregisterHandler("UpdateSubscriptions", []string{string(participant)})
}

func (s *participantServer[ParticipantTopicType]) RegisterForwardParticipantTopic(participant ParticipantTopicType) error {
	return server.RegisterHandler(s.rpc, "ForwardParticipant", []string{string(participant)}, s.svc.ForwardParticipant, nil)
}

func (s *participantServer[ParticipantTopicType]) DeregisterForwardParticipantTopic(participant ParticipantTopicType) {
	s.rpc.DeregisterHandler("ForwardParticipant", []string{string(participant)})
}

func (s *participantServer[ParticipantTopicType]) RegisterMoveParticipantTopic(participant ParticipantTopicType) error {
	return server.RegisterHandler(s.rpc, "MoveParticipant", []string{string(participant)}, s.svc.MoveParticipant, nil)
}

func (s *participantServer[ParticipantTopicType]) DeregisterMoveParticipantTopic(participant ParticipantTopicType) {
	s.rpc.DeregisterHandler("MoveParticipant", []string{string(participant)})
}

func (s *participantServer[ParticipantTopicType]) RegisterPerformRpcTopic(participant ParticipantTopicType) error {
	return server.RegisterHandler(s.rpc, "PerformRpc", []string{string(participant)}, s.svc.PerformRpc, nil)
}

func (s *participantServer[ParticipantTopicType]) DeregisterPerformRpcTopic(participant ParticipantTopicType) {
	s.rpc.DeregisterHandler("PerformRpc", []string{string(participant)})
}

func (s *participantServer[ParticipantTopicType]) allParticipantTopicRegisterers() server.RegistererSlice {
	return server.RegistererSlice{
		server.NewRegisterer(s.RegisterRemoveParticipantTopic, s.DeregisterRemoveParticipantTopic),
		server.NewRegisterer(s.RegisterMutePublishedTrackTopic, s.DeregisterMutePublishedTrackTopic),
		server.NewRegisterer(s.RegisterUpdateParticipantTopic, s.DeregisterUpdateParticipantTopic),
		server.NewRegisterer(s.RegisterUpdateSubscriptionsTopic, s.DeregisterUpdateSubscriptionsTopic),
		server.NewRegisterer(s.RegisterForwardParticipantTopic, s.DeregisterForwardParticipantTopic),
		server.NewRegisterer(s.RegisterMoveParticipantTopic, s.DeregisterMoveParticipantTopic),
		server.NewRegisterer(s.RegisterPerformRpcTopic, s.DeregisterPerformRpcTopic),
	}
}

func (s *participantServer[ParticipantTopicType]) RegisterAllParticipantTopics(participant ParticipantTopicType) error {
	return s.allParticipantTopicRegisterers().Register(participant)
}

func (s *participantServer[ParticipantTopicType]) DeregisterAllParticipantTopics(participant ParticipantTopicType) {
	s.allParticipantTopicRegisterers().Deregister(participant)
}

func (s *participantServer[ParticipantTopicType]) Shutdown() {
	s.rpc.Close(false)
}

func (s *participantServer[ParticipantTopicType]) Kill() {
	s.rpc.Close(true)
}

// ================================
// Participant Unimplemented Server
// ================================

type UnimplementedParticipantServer struct{}

func (UnimplementedParticipantServer) RemoveParticipant(context.Context, *livekit6.RoomParticipantIdentity) (*livekit6.RemoveParticipantResponse, error) {
	return nil, psrpc.ErrUnimplemented
}

func (UnimplementedParticipantServer) MutePublishedTrack(context.Context, *livekit6.MuteRoomTrackRequest) (*livekit6.MuteRoomTrackResponse, error) {
	return nil, psrpc.ErrUnimplemented
}

func (UnimplementedParticipantServer) UpdateParticipant(context.Context, *livekit6.UpdateParticipantRequest) (*livekit1.ParticipantInfo, error) {
	return nil, psrpc.ErrUnimplemented
}

func (UnimplementedParticipantServer) UpdateSubscriptions(context.Context, *livekit6.UpdateSubscriptionsRequest) (*livekit6.UpdateSubscriptionsResponse, error) {
	return nil, psrpc.ErrUnimplemented
}

func (UnimplementedParticipantServer) ForwardParticipant(context.Context, *livekit6.ForwardParticipantRequest) (*livekit6.ForwardParticipantResponse, error) {
	return nil, psrpc.ErrUnimplemented
}

func (UnimplementedParticipantServer) MoveParticipant(context.Context, *livekit6.MoveParticipantRequest) (*livekit6.MoveParticipantResponse, error) {
	return nil, psrpc.ErrUnimplemented
}

func (UnimplementedParticipantServer) PerformRpc(context.Context, *livekit6.PerformRpcRequest) (*livekit6.PerformRpcResponse, error) {
	return nil, psrpc.ErrUnimplemented
}

var psrpcFileDescriptor6 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0x25, 0xfc, 0xa0, 0x87, 0x2d, 0x3f, 0xb4, 0xab, 0x42, 0x89, 0xff, 0x6a, 0x5b, 0x10, 0x0f,
	0x4d, 0x40, 0xbf, 0x81, 0x07, 0xc1, 0x43, 0xa1, 0x44, 0xbd, 0x78, 0x91, 0x64, 0xb3, 0xb5, 0x4b,
	0x93, 0xcc, 0x3a, 0xd9, 0x54, 0xda, 0x8b, 0x07, 0x41, 0xf0, 0xeb, 0xf8, 0xed, 0xbc, 0x49, 0x9b,
	0x26, 0xd9, 0xa6, 0xb6, 0x98, 0xe3, 0xbe, 0xf7, 0xf6, 0xbd, 0xd9, 0x99, 0x59, 0x72, 0x80, 0x92,
	0xd9, 0xd2, 0x45, 0x25, 0x98, 0x90, 0x6e, 0xa4, 0x2c, 0x89, 0xa0, 0x80, 0xfe, 0x43, 0xc9, 0xcc,
	0xff, 0x20, 0x95, 0x80, 0x28, 0x4e, 0x31, 0x73, 0x3f, 0x10, 0x13, 0x3e, 0x16, 0xea, 0x29, 0x04,
	0x9f, 0x07, 0x19, 0x4a, 0x33, 0x14, 0x01, 0xc2, 0x14, 0xbb, 0xfc, 0xae, 0x91, 0xfa, 0xa0, 0xf0,
	0xa4, 0x6f, 0xa4, 0xe1, 0xf0, 0x10, 0x26, 0x5c, 0x07, 0x5b, 0xd6, 0xf2, 0xa6, 0xe5, 0x00, 0x84,
	0x1a, 0x73, 0xeb, 0xf3, 0x48, 0x09, 0x35, 0x35, 0xdb, 0x85, 0xa2, 0x7c, 0xdb, 0xe1, 0xb1, 0x84,
	0x28, 0xe6, 0xed, 0xee, 0xd7, 0xa7, 0xd1, 0xda, 0x35, 0xcc, 0x23, 0x52, 0xd7, 0x5e, 0x41, 0xf5,
	0x43, 0xd3, 0xa0, 0x53, 0x42, 0xfb, 0x89, 0xe2, 0x83, 0xc4, 0x0b, 0x44, 0x3c, 0xe2, 0xfe, 0x3d,
	0xba, 0x6c, 0x4c, 0x8f, 0x73, 0xff, 0x39, 0x39, 0xaf, 0x62, 0x81, 0x3b, 0xfc, 0x25, 0xe1, 0xb1,
	0x32, 0x4f, 0x36, 0xd1, 0x95, 0xa2, 0x27, 0xa4, 0xf1, 0x20, 0x7d, 0x57, 0xad, 0xbc, 0xfd, 0x2c,
	0xb7, 0x5e, 0xe3, 0xb2, 0xf4, 0x66, 0x2e, 0xd1, 0x5b, 0x13, 0x0d, 0xe1, 0x8f, 0xb9, 0x1f, 0x06,
	0xd9, 0x4b, 0xcd, 0xef, 0x12, 0x2f, 0x66, 0x28, 0xd2, 0x59, 0xd2, 0x4e, 0x29, 0x7a, 0x85, 0xcd,
	0xc2, 0xbb, 0xdb, 0x45, 0x95, 0x1a, 0xf0, 0x6e, 0x10, 0x7a, 0x03, 0xf8, 0xea, 0xa2, 0xaf, 0xb7,
	0xa0, 0x18, 0xee, 0x3a, 0x99, 0x95, 0xd1, 0xd9, 0xaa, 0xa9, 0x54, 0xc5, 0x8c, 0xec, 0xf4, 0x4b,
	0x0b, 0x78, 0x5a, 0xcc, 0xb7, 0xbc, 0x5c, 0x69, 0x7c, 0x6b, 0xb3, 0xa0, 0x52, 0xf6, 0x98, 0x90,
	0x01, 0xc7, 0x21, 0x60, 0xe8, 0x48, 0x46, 0xcd, 0x62, 0xb0, 0x39, 0x98, 0x25, 0x1e, 0xfe, 0xca,
	0x55, 0x09, 0xbb, 0xbe, 0x78, 0x3c, 0x7f, 0x16, 0x6a, 0x94, 0x78, 0x16, 0x83, 0xd0, 0x46, 0x3e,
	0x13, 0x3d, 0x01, 0xf6, 0xd2, 0xb6, 0xb7, 0xf8, 0x9f, 0x0c, 0x02, 0x1b, 0x25, 0xf3, 0x6a, 0x8b,
	0xd3, 0xd5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x3c, 0x10, 0xe3, 0x04, 0x04, 0x00, 0x00,
}
