// Code generated by protoc-gen-psrpc v0.7.0, DO NOT EDIT.
// source: rpc/signal.proto

package rpc

import (
	"context"

	"github.com/livekit/psrpc"
	"github.com/livekit/psrpc/pkg/client"
	"github.com/livekit/psrpc/pkg/info"
	"github.com/livekit/psrpc/pkg/rand"
	"github.com/livekit/psrpc/pkg/server"
	"github.com/livekit/psrpc/version"
)

var _ = version.PsrpcVersion_0_7

// =======================
// Signal Client Interface
// =======================

type SignalClient[NodeIdTopicType ~string] interface {
	RelaySignal(ctx context.Context, nodeId NodeIdTopicType, opts ...psrpc.RequestOption) (psrpc.ClientStream[*RelaySignalRequest, *RelaySignalResponse], error)

	// Close immediately, without waiting for pending RPCs
	Close()
}

// ===========================
// Signal ServerImpl Interface
// ===========================

type SignalServerImpl interface {
	RelaySignal(psrpc.ServerStream[*RelaySignalResponse, *RelaySignalRequest]) error
}

// =======================
// Signal Server Interface
// =======================

type SignalServer[NodeIdTopicType ~string] interface {
	RegisterRelaySignalTopic(nodeId NodeIdTopicType) error
	DeregisterRelaySignalTopic(nodeId NodeIdTopicType)
	RegisterAllNodeTopics(nodeId NodeIdTopicType) error
	DeregisterAllNodeTopics(nodeId NodeIdTopicType)

	// Close and wait for pending RPCs to complete
	Shutdown()

	// Close immediately, without waiting for pending RPCs
	Kill()
}

// =============
// Signal Client
// =============

type signalClient[NodeIdTopicType ~string] struct {
	client *client.RPCClient
}

// NewSignalClient creates a psrpc client that implements the SignalClient interface.
func NewSignalClient[NodeIdTopicType ~string](bus psrpc.MessageBus, opts ...psrpc.ClientOption) (SignalClient[NodeIdTopicType], error) {
	sd := &info.ServiceDefinition{
		Name: "Signal",
		ID:   rand.NewClientID(),
	}

	sd.RegisterMethod("RelaySignal", false, false, false, true)

	rpcClient, err := client.NewRPCClientWithStreams(sd, bus, opts...)
	if err != nil {
		return nil, err
	}

	return &signalClient[NodeIdTopicType]{
		client: rpcClient,
	}, nil
}

func (c *signalClient[NodeIdTopicType]) RelaySignal(ctx context.Context, nodeId NodeIdTopicType, opts ...psrpc.RequestOption) (psrpc.ClientStream[*RelaySignalRequest, *RelaySignalResponse], error) {
	return client.OpenStream[*RelaySignalRequest, *RelaySignalResponse](ctx, c.client, "RelaySignal", []string{string(nodeId)}, opts...)
}

func (s *signalClient[NodeIdTopicType]) Close() {
	s.client.Close()
}

// =============
// Signal Server
// =============

type signalServer[NodeIdTopicType ~string] struct {
	svc SignalServerImpl
	rpc *server.RPCServer
}

// NewSignalServer builds a RPCServer that will route requests
// to the corresponding method in the provided svc implementation.
func NewSignalServer[NodeIdTopicType ~string](svc SignalServerImpl, bus psrpc.MessageBus, opts ...psrpc.ServerOption) (SignalServer[NodeIdTopicType], error) {
	sd := &info.ServiceDefinition{
		Name: "Signal",
		ID:   rand.NewServerID(),
	}

	s := server.NewRPCServer(sd, bus, opts...)

	sd.RegisterMethod("RelaySignal", false, false, false, true)
	return &signalServer[NodeIdTopicType]{
		svc: svc,
		rpc: s,
	}, nil
}

func (s *signalServer[NodeIdTopicType]) RegisterRelaySignalTopic(nodeId NodeIdTopicType) error {
	return server.RegisterStreamHandler(s.rpc, "RelaySignal", []string{string(nodeId)}, s.svc.RelaySignal, nil)
}

func (s *signalServer[NodeIdTopicType]) DeregisterRelaySignalTopic(nodeId NodeIdTopicType) {
	s.rpc.DeregisterHandler("RelaySignal", []string{string(nodeId)})
}

func (s *signalServer[NodeIdTopicType]) allNodeTopicRegisterers() server.RegistererSlice {
	return server.RegistererSlice{
		server.NewRegisterer(s.RegisterRelaySignalTopic, s.DeregisterRelaySignalTopic),
	}
}

func (s *signalServer[NodeIdTopicType]) RegisterAllNodeTopics(nodeId NodeIdTopicType) error {
	return s.allNodeTopicRegisterers().Register(nodeId)
}

func (s *signalServer[NodeIdTopicType]) DeregisterAllNodeTopics(nodeId NodeIdTopicType) {
	s.allNodeTopicRegisterers().Deregister(nodeId)
}

func (s *signalServer[NodeIdTopicType]) Shutdown() {
	s.rpc.Close(false)
}

func (s *signalServer[NodeIdTopicType]) Kill() {
	s.rpc.Close(true)
}

// ===========================
// Signal Unimplemented Server
// ===========================

type UnimplementedSignalServer struct{}

func (UnimplementedSignalServer) RelaySignal(psrpc.ServerStream[*RelaySignalResponse, *RelaySignalRequest]) error {
	return psrpc.ErrUnimplemented
}

var psrpcFileDescriptor9 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0x65, 0x92, 0x96, 0xe2, 0x52, 0xa9, 0xb8, 0xd0, 0x86, 0x48, 0x48, 0x51, 0x37, 0x84,
	0x45, 0x1d, 0x29, 0x88, 0x0d, 0x4b, 0x8e, 0xe0, 0xee, 0xd8, 0x44, 0xad, 0x6b, 0x15, 0x8b, 0x60,
	0xbb, 0x1e, 0x17, 0x09, 0x6e, 0xc0, 0x5d, 0x58, 0x71, 0x42, 0x94, 0xb8, 0x3f, 0x41, 0x61, 0x13,
	0xcd, 0xcc, 0x7b, 0x79, 0x9f, 0x3d, 0xc6, 0x43, 0x6b, 0x78, 0x06, 0x72, 0xad, 0x16, 0x25, 0x35,
	0x56, 0x3b, 0x4d, 0x02, 0x6b, 0x78, 0x3c, 0xd0, 0xc6, 0x49, 0xad, 0xc0, 0xcf, 0xe2, 0x71, 0x29,
	0xdf, 0xc5, 0xab, 0x74, 0x85, 0x54, 0x4e, 0xd8, 0x83, 0x37, 0xbe, 0xd8, 0xcf, 0xad, 0xe3, 0x7e,
	0x34, 0xfd, 0x46, 0x98, 0x30, 0x51, 0x2e, 0x3e, 0xe6, 0x75, 0x28, 0x13, 0x9b, 0xad, 0x00, 0x47,
	0x1e, 0xf1, 0x00, 0xdc, 0xc2, 0xba, 0x02, 0x04, 0x80, 0xd4, 0x2a, 0x42, 0x09, 0x4a, 0xfb, 0xf9,
	0x15, 0xdd, 0x25, 0xd0, 0x79, 0xa5, 0xce, 0xbd, 0xc8, 0xce, 0xa1, 0xd1, 0x91, 0x1c, 0xf7, 0xac,
	0x8f, 0x81, 0x28, 0x48, 0x82, 0xb4, 0x9f, 0x8f, 0x8f, 0xbf, 0x35, 0x29, 0xec, 0xe0, 0x23, 0x43,
	0x1c, 0x80, 0xd8, 0x44, 0x61, 0x82, 0xd2, 0x90, 0x55, 0x25, 0xb9, 0xc4, 0x1d, 0x5e, 0x6a, 0x10,
	0x51, 0x27, 0x41, 0x69, 0x8f, 0xf9, 0x66, 0xea, 0xf0, 0xe8, 0xcf, 0x69, 0xc1, 0x68, 0x05, 0x82,
	0x3c, 0xe0, 0x33, 0xbb, 0xab, 0x21, 0x3a, 0xa9, 0x99, 0x93, 0x16, 0xd3, 0xeb, 0xec, 0xe8, 0xdc,
	0x53, 0x83, 0x7f, 0xa8, 0x61, 0x83, 0x9a, 0x4b, 0xdc, 0xf5, 0x21, 0xa4, 0xc0, 0xfd, 0x06, 0x9f,
	0x4c, 0xa8, 0x35, 0x9c, 0xb6, 0xf7, 0x17, 0x47, 0x6d, 0xc1, 0x43, 0xa7, 0x37, 0x3f, 0x5f, 0xe8,
	0x7a, 0x88, 0xe2, 0x11, 0x0e, 0x95, 0x5e, 0x09, 0x72, 0x5a, 0x7d, 0x0b, 0xb9, 0xaa, 0x36, 0x9c,
	0xa0, 0xa7, 0xbb, 0xe7, 0xdb, 0xb5, 0x74, 0x2f, 0xdb, 0x25, 0xe5, 0xfa, 0x2d, 0xb3, 0xe2, 0x53,
	0xce, 0xa4, 0xce, 0x76, 0x57, 0x99, 0xd5, 0x6f, 0xc6, 0x75, 0x99, 0x59, 0xc3, 0x97, 0xdd, 0xba,
	0xbb, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x10, 0x5b, 0x3f, 0x1b, 0x14, 0x02, 0x00, 0x00,
}
