// Code generated by protoc-gen-psrpc v0.7.0, DO NOT EDIT.
// source: rpc/whip_signal.proto

package rpc

import (
	"context"

	"github.com/livekit/psrpc"
	"github.com/livekit/psrpc/pkg/client"
	"github.com/livekit/psrpc/pkg/info"
	"github.com/livekit/psrpc/pkg/rand"
	"github.com/livekit/psrpc/pkg/server"
	"github.com/livekit/psrpc/version"
)
import google_protobuf "google.golang.org/protobuf/types/known/emptypb"

var _ = version.PsrpcVersion_0_7

// =====================
// WHIP Client Interface
// =====================

type WHIPClient[TopicTopicType ~string] interface {
	Create(ctx context.Context, topic TopicTopicType, req *WHIPCreateRequest, opts ...psrpc.RequestOption) (*WHIPCreateResponse, error)

	// Close immediately, without waiting for pending RPCs
	Close()
}

// =========================
// WHIP ServerImpl Interface
// =========================

type WHIPServerImpl interface {
	Create(context.Context, *WHIPCreateRequest) (*WHIPCreateResponse, error)
}

// =====================
// WHIP Server Interface
// =====================

type WHIPServer[TopicTopicType ~string] interface {
	RegisterCreateTopic(topic TopicTopicType) error
	DeregisterCreateTopic(topic TopicTopicType)
	RegisterAllCommonTopics(topic TopicTopicType) error
	DeregisterAllCommonTopics(topic TopicTopicType)

	// Close and wait for pending RPCs to complete
	Shutdown()

	// Close immediately, without waiting for pending RPCs
	Kill()
}

// ===========
// WHIP Client
// ===========

type wHIPClient[TopicTopicType ~string] struct {
	client *client.RPCClient
}

// NewWHIPClient creates a psrpc client that implements the WHIPClient interface.
func NewWHIPClient[TopicTopicType ~string](bus psrpc.MessageBus, opts ...psrpc.ClientOption) (WHIPClient[TopicTopicType], error) {
	sd := &info.ServiceDefinition{
		Name: "WHIP",
		ID:   rand.NewClientID(),
	}

	sd.RegisterMethod("Create", false, false, true, true)

	rpcClient, err := client.NewRPCClient(sd, bus, opts...)
	if err != nil {
		return nil, err
	}

	return &wHIPClient[TopicTopicType]{
		client: rpcClient,
	}, nil
}

func (c *wHIPClient[TopicTopicType]) Create(ctx context.Context, topic TopicTopicType, req *WHIPCreateRequest, opts ...psrpc.RequestOption) (*WHIPCreateResponse, error) {
	return client.RequestSingle[*WHIPCreateResponse](ctx, c.client, "Create", []string{string(topic)}, req, opts...)
}

func (s *wHIPClient[TopicTopicType]) Close() {
	s.client.Close()
}

// ===========
// WHIP Server
// ===========

type wHIPServer[TopicTopicType ~string] struct {
	svc WHIPServerImpl
	rpc *server.RPCServer
}

// NewWHIPServer builds a RPCServer that will route requests
// to the corresponding method in the provided svc implementation.
func NewWHIPServer[TopicTopicType ~string](svc WHIPServerImpl, bus psrpc.MessageBus, opts ...psrpc.ServerOption) (WHIPServer[TopicTopicType], error) {
	sd := &info.ServiceDefinition{
		Name: "WHIP",
		ID:   rand.NewServerID(),
	}

	s := server.NewRPCServer(sd, bus, opts...)

	sd.RegisterMethod("Create", false, false, true, true)
	return &wHIPServer[TopicTopicType]{
		svc: svc,
		rpc: s,
	}, nil
}

func (s *wHIPServer[TopicTopicType]) RegisterCreateTopic(topic TopicTopicType) error {
	return server.RegisterHandler(s.rpc, "Create", []string{string(topic)}, s.svc.Create, nil)
}

func (s *wHIPServer[TopicTopicType]) DeregisterCreateTopic(topic TopicTopicType) {
	s.rpc.DeregisterHandler("Create", []string{string(topic)})
}

func (s *wHIPServer[TopicTopicType]) allCommonTopicRegisterers() server.RegistererSlice {
	return server.RegistererSlice{
		server.NewRegisterer(s.RegisterCreateTopic, s.DeregisterCreateTopic),
	}
}

func (s *wHIPServer[TopicTopicType]) RegisterAllCommonTopics(topic TopicTopicType) error {
	return s.allCommonTopicRegisterers().Register(topic)
}

func (s *wHIPServer[TopicTopicType]) DeregisterAllCommonTopics(topic TopicTopicType) {
	s.allCommonTopicRegisterers().Deregister(topic)
}

func (s *wHIPServer[TopicTopicType]) Shutdown() {
	s.rpc.Close(false)
}

func (s *wHIPServer[TopicTopicType]) Kill() {
	s.rpc.Close(true)
}

// =========================
// WHIP Unimplemented Server
// =========================

type UnimplementedWHIPServer struct{}

func (UnimplementedWHIPServer) Create(context.Context, *WHIPCreateRequest) (*WHIPCreateResponse, error) {
	return nil, psrpc.ErrUnimplemented
}

// ================================
// WHIPParticipant Client Interface
// ================================

type WHIPParticipantClient[TopicTopicType ~string] interface {
	ICETrickle(ctx context.Context, topic TopicTopicType, req *WHIPParticipantICETrickleRequest, opts ...psrpc.RequestOption) (*google_protobuf.Empty, error)

	ICERestart(ctx context.Context, topic TopicTopicType, req *WHIPParticipantICERestartRequest, opts ...psrpc.RequestOption) (*WHIPParticipantICERestartResponse, error)

	DeleteSession(ctx context.Context, topic TopicTopicType, req *WHIPParticipantDeleteSessionRequest, opts ...psrpc.RequestOption) (*google_protobuf.Empty, error)

	// Close immediately, without waiting for pending RPCs
	Close()
}

// ====================================
// WHIPParticipant ServerImpl Interface
// ====================================

type WHIPParticipantServerImpl interface {
	ICETrickle(context.Context, *WHIPParticipantICETrickleRequest) (*google_protobuf.Empty, error)

	ICERestart(context.Context, *WHIPParticipantICERestartRequest) (*WHIPParticipantICERestartResponse, error)

	DeleteSession(context.Context, *WHIPParticipantDeleteSessionRequest) (*google_protobuf.Empty, error)
}

// ================================
// WHIPParticipant Server Interface
// ================================

type WHIPParticipantServer[TopicTopicType ~string] interface {
	RegisterICETrickleTopic(topic TopicTopicType) error
	DeregisterICETrickleTopic(topic TopicTopicType)
	RegisterICERestartTopic(topic TopicTopicType) error
	DeregisterICERestartTopic(topic TopicTopicType)
	RegisterDeleteSessionTopic(topic TopicTopicType) error
	DeregisterDeleteSessionTopic(topic TopicTopicType)
	RegisterAllCommonTopics(topic TopicTopicType) error
	DeregisterAllCommonTopics(topic TopicTopicType)

	// Close and wait for pending RPCs to complete
	Shutdown()

	// Close immediately, without waiting for pending RPCs
	Kill()
}

// ======================
// WHIPParticipant Client
// ======================

type wHIPParticipantClient[TopicTopicType ~string] struct {
	client *client.RPCClient
}

// NewWHIPParticipantClient creates a psrpc client that implements the WHIPParticipantClient interface.
func NewWHIPParticipantClient[TopicTopicType ~string](bus psrpc.MessageBus, opts ...psrpc.ClientOption) (WHIPParticipantClient[TopicTopicType], error) {
	sd := &info.ServiceDefinition{
		Name: "WHIPParticipant",
		ID:   rand.NewClientID(),
	}

	sd.RegisterMethod("ICETrickle", false, false, true, true)
	sd.RegisterMethod("ICERestart", false, false, true, true)
	sd.RegisterMethod("DeleteSession", false, false, true, true)

	rpcClient, err := client.NewRPCClient(sd, bus, opts...)
	if err != nil {
		return nil, err
	}

	return &wHIPParticipantClient[TopicTopicType]{
		client: rpcClient,
	}, nil
}

func (c *wHIPParticipantClient[TopicTopicType]) ICETrickle(ctx context.Context, topic TopicTopicType, req *WHIPParticipantICETrickleRequest, opts ...psrpc.RequestOption) (*google_protobuf.Empty, error) {
	return client.RequestSingle[*google_protobuf.Empty](ctx, c.client, "ICETrickle", []string{string(topic)}, req, opts...)
}

func (c *wHIPParticipantClient[TopicTopicType]) ICERestart(ctx context.Context, topic TopicTopicType, req *WHIPParticipantICERestartRequest, opts ...psrpc.RequestOption) (*WHIPParticipantICERestartResponse, error) {
	return client.RequestSingle[*WHIPParticipantICERestartResponse](ctx, c.client, "ICERestart", []string{string(topic)}, req, opts...)
}

func (c *wHIPParticipantClient[TopicTopicType]) DeleteSession(ctx context.Context, topic TopicTopicType, req *WHIPParticipantDeleteSessionRequest, opts ...psrpc.RequestOption) (*google_protobuf.Empty, error) {
	return client.RequestSingle[*google_protobuf.Empty](ctx, c.client, "DeleteSession", []string{string(topic)}, req, opts...)
}

func (s *wHIPParticipantClient[TopicTopicType]) Close() {
	s.client.Close()
}

// ======================
// WHIPParticipant Server
// ======================

type wHIPParticipantServer[TopicTopicType ~string] struct {
	svc WHIPParticipantServerImpl
	rpc *server.RPCServer
}

// NewWHIPParticipantServer builds a RPCServer that will route requests
// to the corresponding method in the provided svc implementation.
func NewWHIPParticipantServer[TopicTopicType ~string](svc WHIPParticipantServerImpl, bus psrpc.MessageBus, opts ...psrpc.ServerOption) (WHIPParticipantServer[TopicTopicType], error) {
	sd := &info.ServiceDefinition{
		Name: "WHIPParticipant",
		ID:   rand.NewServerID(),
	}

	s := server.NewRPCServer(sd, bus, opts...)

	sd.RegisterMethod("ICETrickle", false, false, true, true)
	sd.RegisterMethod("ICERestart", false, false, true, true)
	sd.RegisterMethod("DeleteSession", false, false, true, true)
	return &wHIPParticipantServer[TopicTopicType]{
		svc: svc,
		rpc: s,
	}, nil
}

func (s *wHIPParticipantServer[TopicTopicType]) RegisterICETrickleTopic(topic TopicTopicType) error {
	return server.RegisterHandler(s.rpc, "ICETrickle", []string{string(topic)}, s.svc.ICETrickle, nil)
}

func (s *wHIPParticipantServer[TopicTopicType]) DeregisterICETrickleTopic(topic TopicTopicType) {
	s.rpc.DeregisterHandler("ICETrickle", []string{string(topic)})
}

func (s *wHIPParticipantServer[TopicTopicType]) RegisterICERestartTopic(topic TopicTopicType) error {
	return server.RegisterHandler(s.rpc, "ICERestart", []string{string(topic)}, s.svc.ICERestart, nil)
}

func (s *wHIPParticipantServer[TopicTopicType]) DeregisterICERestartTopic(topic TopicTopicType) {
	s.rpc.DeregisterHandler("ICERestart", []string{string(topic)})
}

func (s *wHIPParticipantServer[TopicTopicType]) RegisterDeleteSessionTopic(topic TopicTopicType) error {
	return server.RegisterHandler(s.rpc, "DeleteSession", []string{string(topic)}, s.svc.DeleteSession, nil)
}

func (s *wHIPParticipantServer[TopicTopicType]) DeregisterDeleteSessionTopic(topic TopicTopicType) {
	s.rpc.DeregisterHandler("DeleteSession", []string{string(topic)})
}

func (s *wHIPParticipantServer[TopicTopicType]) allCommonTopicRegisterers() server.RegistererSlice {
	return server.RegistererSlice{
		server.NewRegisterer(s.RegisterICETrickleTopic, s.DeregisterICETrickleTopic),
		server.NewRegisterer(s.RegisterICERestartTopic, s.DeregisterICERestartTopic),
		server.NewRegisterer(s.RegisterDeleteSessionTopic, s.DeregisterDeleteSessionTopic),
	}
}

func (s *wHIPParticipantServer[TopicTopicType]) RegisterAllCommonTopics(topic TopicTopicType) error {
	return s.allCommonTopicRegisterers().Register(topic)
}

func (s *wHIPParticipantServer[TopicTopicType]) DeregisterAllCommonTopics(topic TopicTopicType) {
	s.allCommonTopicRegisterers().Deregister(topic)
}

func (s *wHIPParticipantServer[TopicTopicType]) Shutdown() {
	s.rpc.Close(false)
}

func (s *wHIPParticipantServer[TopicTopicType]) Kill() {
	s.rpc.Close(true)
}

// ====================================
// WHIPParticipant Unimplemented Server
// ====================================

type UnimplementedWHIPParticipantServer struct{}

func (UnimplementedWHIPParticipantServer) ICETrickle(context.Context, *WHIPParticipantICETrickleRequest) (*google_protobuf.Empty, error) {
	return nil, psrpc.ErrUnimplemented
}

func (UnimplementedWHIPParticipantServer) ICERestart(context.Context, *WHIPParticipantICERestartRequest) (*WHIPParticipantICERestartResponse, error) {
	return nil, psrpc.ErrUnimplemented
}

func (UnimplementedWHIPParticipantServer) DeleteSession(context.Context, *WHIPParticipantDeleteSessionRequest) (*google_protobuf.Empty, error) {
	return nil, psrpc.ErrUnimplemented
}

var psrpcFileDescriptor10 = []byte{
	// 731 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xdf, 0x6e, 0xd3, 0x3e,
	0x14, 0x56, 0xda, 0x6e, 0x5a, 0x4f, 0xd7, 0xfd, 0x36, 0xff, 0xd8, 0x56, 0x52, 0x4d, 0x64, 0x85,
	0x41, 0x91, 0x58, 0x2a, 0x3a, 0x09, 0xa6, 0x5d, 0x32, 0x8a, 0xa8, 0x84, 0xd0, 0x94, 0x4e, 0x20,
	0x71, 0x41, 0x94, 0x3a, 0x6e, 0x67, 0x35, 0x89, 0x8d, 0xed, 0x76, 0x2a, 0x3c, 0xc1, 0xde, 0x85,
	0xab, 0x21, 0x78, 0x17, 0xae, 0x78, 0x15, 0x14, 0x27, 0xed, 0xda, 0xb5, 0xfb, 0x23, 0x6e, 0x76,
	0x67, 0x7f, 0x3e, 0x3e, 0xe7, 0x3b, 0xdf, 0x39, 0xc7, 0x86, 0x75, 0xc1, 0x71, 0xed, 0xf4, 0x84,
	0x72, 0x57, 0xd2, 0x6e, 0xe4, 0x05, 0x36, 0x17, 0x4c, 0x31, 0x94, 0x15, 0x1c, 0x9b, 0xe5, 0x2e,
	0x63, 0xdd, 0x80, 0xd4, 0x34, 0xd4, 0xee, 0x77, 0x6a, 0x24, 0xe4, 0x6a, 0x98, 0x58, 0x98, 0x45,
	0xc6, 0x15, 0x65, 0x91, 0x4c, 0xb7, 0x1b, 0x01, 0x1d, 0x90, 0x1e, 0x55, 0x2e, 0x8d, 0x14, 0x11,
	0x63, 0x47, 0xe6, 0xda, 0x08, 0x17, 0x0a, 0x27, 0x50, 0xe5, 0x7b, 0x16, 0xd6, 0x3e, 0xbe, 0x6d,
	0x1e, 0x1d, 0x0a, 0xe2, 0x29, 0xe2, 0x90, 0x2f, 0x7d, 0x22, 0x15, 0x3a, 0x80, 0xa2, 0x54, 0x9e,
	0x50, 0xae, 0x24, 0x52, 0x52, 0x16, 0x95, 0x0c, 0xcb, 0xa8, 0x16, 0xea, 0xeb, 0x76, 0xea, 0xc0,
	0x6e, 0xc5, 0xa7, 0xad, 0xe4, 0xd0, 0x59, 0x96, 0x13, 0x3b, 0x54, 0x86, 0x3c, 0xeb, 0x74, 0x88,
	0x70, 0xa5, 0xcf, 0x4b, 0x19, 0xcb, 0xa8, 0xe6, 0x9d, 0x25, 0x0d, 0xb4, 0x7c, 0x8e, 0xbe, 0xc1,
	0x96, 0xec, 0xb7, 0x25, 0x16, 0xb4, 0x4d, 0x7c, 0x97, 0x7b, 0x42, 0x51, 0x4c, 0xb9, 0x17, 0x29,
	0x57, 0x09, 0x0f, 0xf7, 0x64, 0x29, 0x6b, 0x65, 0xab, 0x85, 0xfa, 0x4b, 0x5b, 0x70, 0x6c, 0xcf,
	0xf0, 0xb2, 0x5b, 0xe3, 0xbb, 0x47, 0x17, 0x57, 0x8f, 0xf5, 0xcd, 0x46, 0xa4, 0xc4, 0xd0, 0x29,
	0xcb, 0xab, 0x2d, 0xd0, 0x36, 0x2c, 0x77, 0x04, 0x0b, 0x5d, 0x1a, 0x75, 0x05, 0x91, 0xb2, 0x94,
	0xb3, 0x8c, 0xea, 0x92, 0x53, 0x88, 0xb1, 0x66, 0x02, 0x99, 0xcf, 0x20, 0xaf, 0x8d, 0xdf, 0x51,
	0xa9, 0xd0, 0x03, 0x28, 0x68, 0x56, 0x6e, 0xe4, 0x85, 0x44, 0x96, 0x0c, 0x2b, 0x5b, 0xcd, 0x3b,
	0xa0, 0xa1, 0xf7, 0x31, 0x62, 0x72, 0xb0, 0x6e, 0x62, 0x84, 0x56, 0x21, 0xdb, 0x23, 0x43, 0x2d,
	0x60, 0xde, 0x89, 0x97, 0xe8, 0x05, 0x2c, 0x0c, 0xbc, 0xa0, 0x4f, 0xb4, 0x38, 0x85, 0xba, 0x75,
	0x45, 0xae, 0x63, 0x1e, 0x4e, 0x62, 0x7e, 0x90, 0xd9, 0x37, 0x2a, 0x3f, 0x0d, 0x40, 0x93, 0xa6,
	0x92, 0xb3, 0x48, 0x12, 0xb4, 0x05, 0xe0, 0x45, 0xf2, 0x34, 0x15, 0x3d, 0x89, 0x95, 0x4f, 0x90,
	0x58, 0xf5, 0x1d, 0x58, 0x99, 0x94, 0x9a, 0xfa, 0x69, 0x5d, 0x8a, 0x13, 0x68, 0xd3, 0x47, 0x7b,
	0x50, 0xa0, 0x98, 0xb8, 0x92, 0x88, 0x01, 0x11, 0xa3, 0x52, 0xa0, 0x71, 0xcd, 0x9b, 0x87, 0x8d,
	0x96, 0x3e, 0x72, 0x80, 0x62, 0x92, 0x2c, 0x25, 0x7a, 0x04, 0x2b, 0xc9, 0x25, 0x5d, 0xfd, 0xd8,
	0x77, 0x4e, 0xfb, 0x5e, 0xd6, 0x36, 0x1a, 0x6c, 0xfa, 0x95, 0xdf, 0x06, 0x58, 0x31, 0xef, 0x09,
	0x91, 0x9a, 0x87, 0x8d, 0x63, 0x41, 0x71, 0x2f, 0x18, 0x77, 0x1d, 0x82, 0x9c, 0x60, 0x2c, 0x4c,
	0xf9, 0xeb, 0x35, 0x7a, 0x0e, 0xf7, 0xa6, 0xa9, 0x93, 0x48, 0x51, 0x35, 0x4c, 0x13, 0xf8, 0x7f,
	0x2a, 0x81, 0xe4, 0x68, 0x4e, 0xb6, 0xd9, 0x79, 0xd9, 0xde, 0x8a, 0x78, 0xdc, 0x33, 0xd2, 0xe7,
	0x6e, 0x47, 0x78, 0xdd, 0x90, 0x44, 0xaa, 0xb4, 0xa0, 0x6d, 0x0a, 0xd2, 0xe7, 0x6f, 0x52, 0xa8,
	0xf2, 0x63, 0x6e, 0x6e, 0x0e, 0xd1, 0x53, 0x71, 0x37, 0xb9, 0x5d, 0x66, 0x9d, 0x9b, 0x65, 0x1d,
	0xc0, 0xf6, 0x35, 0xa4, 0xd3, 0xbe, 0x9a, 0xd5, 0xc8, 0xb8, 0x85, 0x46, 0x99, 0xd9, 0x68, 0xbf,
	0x0c, 0x78, 0x78, 0x29, 0xdc, 0x6b, 0x12, 0x10, 0x35, 0xf2, 0x72, 0x67, 0x32, 0xe9, 0x07, 0x41,
	0x9e, 0x12, 0xc2, 0x89, 0x98, 0x7c, 0x10, 0x5a, 0x09, 0x54, 0xff, 0x0c, 0xb9, 0x98, 0x37, 0xfa,
	0x00, 0x8b, 0xc9, 0xcc, 0xa1, 0x8d, 0xf9, 0xf3, 0x6a, 0x6e, 0xce, 0xe0, 0x89, 0x88, 0x95, 0xf2,
	0xf9, 0x99, 0xb1, 0xb9, 0x6a, 0x98, 0x6b, 0xb0, 0x88, 0x59, 0x18, 0xb2, 0x08, 0x2d, 0x28, 0xc6,
	0x29, 0x2e, 0x19, 0xfb, 0x46, 0xfd, 0x4f, 0x06, 0xfe, 0xbb, 0x24, 0x0c, 0xea, 0x00, 0x5c, 0x0c,
	0x07, 0xda, 0x19, 0xfb, 0xbd, 0x6e, 0x78, 0xcc, 0x0d, 0x3b, 0xf9, 0x20, 0xec, 0xd1, 0x07, 0x61,
	0x37, 0xe2, 0x0f, 0xa2, 0x72, 0xff, 0xfc, 0xcc, 0x58, 0x9f, 0x1b, 0x1d, 0x0d, 0x74, 0x9c, 0xb4,
	0xe6, 0x57, 0xc6, 0x99, 0x6e, 0x64, 0xf3, 0xf1, 0x4d, 0x66, 0x69, 0xd6, 0xd7, 0xc4, 0x0d, 0xa0,
	0x38, 0x55, 0x7c, 0x54, 0x9d, 0xe7, 0x73, 0x5e, 0x7f, 0xfc, 0x43, 0x96, 0xaf, 0x9e, 0x7e, 0x7a,
	0xd2, 0xa5, 0xea, 0xa4, 0xdf, 0xb6, 0x31, 0x0b, 0x6b, 0x82, 0x7c, 0xa5, 0xbb, 0x94, 0xd5, 0xd2,
	0x47, 0x6d, 0x57, 0xfb, 0xc1, 0x2c, 0xa8, 0x09, 0x8e, 0xdb, 0x8b, 0x7a, 0xb7, 0xf7, 0x37, 0x00,
	0x00, 0xff, 0xff, 0xad, 0xef, 0xb4, 0xc0, 0x88, 0x07, 0x00, 0x00,
}
