// Code generated by protoc-gen-twirp v8.1.3, DO NOT EDIT.
// source: livekit_phone_number.proto

package livekit

import context "context"
import fmt "fmt"
import http "net/http"
import io "io"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// ============================
// PhoneNumberService Interface
// ============================

// Public Phone Number Service - External API for phone number management
type PhoneNumberService interface {
	// Search available phone numbers in inventory
	SearchPhoneNumbers(context.Context, *SearchPhoneNumbersRequest) (*SearchPhoneNumbersResponse, error)

	// Purchase a phone number from inventory
	PurchasePhoneNumber(context.Context, *PurchasePhoneNumberRequest) (*PurchasePhoneNumberResponse, error)

	// List phone numbers for a project
	ListPhoneNumbers(context.Context, *ListPhoneNumbersRequest) (*ListPhoneNumbersResponse, error)

	// Get a phone number from a project
	GetPhoneNumber(context.Context, *GetPhoneNumberRequest) (*GetPhoneNumberResponse, error)

	// Update a phone number in a project
	UpdatePhoneNumber(context.Context, *UpdatePhoneNumberRequest) (*UpdatePhoneNumberResponse, error)

	// Release phone numbers
	ReleasePhoneNumbers(context.Context, *ReleasePhoneNumbersRequest) (*ReleasePhoneNumbersResponse, error)
}

// ==================================
// PhoneNumberService Protobuf Client
// ==================================

type phoneNumberServiceProtobufClient struct {
	client      HTTPClient
	urls        [6]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewPhoneNumberServiceProtobufClient creates a Protobuf client that implements the PhoneNumberService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewPhoneNumberServiceProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) PhoneNumberService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "livekit", "PhoneNumberService")
	urls := [6]string{
		serviceURL + "SearchPhoneNumbers",
		serviceURL + "PurchasePhoneNumber",
		serviceURL + "ListPhoneNumbers",
		serviceURL + "GetPhoneNumber",
		serviceURL + "UpdatePhoneNumber",
		serviceURL + "ReleasePhoneNumbers",
	}

	return &phoneNumberServiceProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *phoneNumberServiceProtobufClient) SearchPhoneNumbers(ctx context.Context, in *SearchPhoneNumbersRequest) (*SearchPhoneNumbersResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "PhoneNumberService")
	ctx = ctxsetters.WithMethodName(ctx, "SearchPhoneNumbers")
	caller := c.callSearchPhoneNumbers
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *SearchPhoneNumbersRequest) (*SearchPhoneNumbersResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SearchPhoneNumbersRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SearchPhoneNumbersRequest) when calling interceptor")
					}
					return c.callSearchPhoneNumbers(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SearchPhoneNumbersResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SearchPhoneNumbersResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *phoneNumberServiceProtobufClient) callSearchPhoneNumbers(ctx context.Context, in *SearchPhoneNumbersRequest) (*SearchPhoneNumbersResponse, error) {
	out := new(SearchPhoneNumbersResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *phoneNumberServiceProtobufClient) PurchasePhoneNumber(ctx context.Context, in *PurchasePhoneNumberRequest) (*PurchasePhoneNumberResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "PhoneNumberService")
	ctx = ctxsetters.WithMethodName(ctx, "PurchasePhoneNumber")
	caller := c.callPurchasePhoneNumber
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *PurchasePhoneNumberRequest) (*PurchasePhoneNumberResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*PurchasePhoneNumberRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*PurchasePhoneNumberRequest) when calling interceptor")
					}
					return c.callPurchasePhoneNumber(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*PurchasePhoneNumberResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*PurchasePhoneNumberResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *phoneNumberServiceProtobufClient) callPurchasePhoneNumber(ctx context.Context, in *PurchasePhoneNumberRequest) (*PurchasePhoneNumberResponse, error) {
	out := new(PurchasePhoneNumberResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *phoneNumberServiceProtobufClient) ListPhoneNumbers(ctx context.Context, in *ListPhoneNumbersRequest) (*ListPhoneNumbersResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "PhoneNumberService")
	ctx = ctxsetters.WithMethodName(ctx, "ListPhoneNumbers")
	caller := c.callListPhoneNumbers
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListPhoneNumbersRequest) (*ListPhoneNumbersResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListPhoneNumbersRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListPhoneNumbersRequest) when calling interceptor")
					}
					return c.callListPhoneNumbers(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListPhoneNumbersResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListPhoneNumbersResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *phoneNumberServiceProtobufClient) callListPhoneNumbers(ctx context.Context, in *ListPhoneNumbersRequest) (*ListPhoneNumbersResponse, error) {
	out := new(ListPhoneNumbersResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *phoneNumberServiceProtobufClient) GetPhoneNumber(ctx context.Context, in *GetPhoneNumberRequest) (*GetPhoneNumberResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "PhoneNumberService")
	ctx = ctxsetters.WithMethodName(ctx, "GetPhoneNumber")
	caller := c.callGetPhoneNumber
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetPhoneNumberRequest) (*GetPhoneNumberResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetPhoneNumberRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetPhoneNumberRequest) when calling interceptor")
					}
					return c.callGetPhoneNumber(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetPhoneNumberResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetPhoneNumberResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *phoneNumberServiceProtobufClient) callGetPhoneNumber(ctx context.Context, in *GetPhoneNumberRequest) (*GetPhoneNumberResponse, error) {
	out := new(GetPhoneNumberResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *phoneNumberServiceProtobufClient) UpdatePhoneNumber(ctx context.Context, in *UpdatePhoneNumberRequest) (*UpdatePhoneNumberResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "PhoneNumberService")
	ctx = ctxsetters.WithMethodName(ctx, "UpdatePhoneNumber")
	caller := c.callUpdatePhoneNumber
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UpdatePhoneNumberRequest) (*UpdatePhoneNumberResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdatePhoneNumberRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdatePhoneNumberRequest) when calling interceptor")
					}
					return c.callUpdatePhoneNumber(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*UpdatePhoneNumberResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*UpdatePhoneNumberResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *phoneNumberServiceProtobufClient) callUpdatePhoneNumber(ctx context.Context, in *UpdatePhoneNumberRequest) (*UpdatePhoneNumberResponse, error) {
	out := new(UpdatePhoneNumberResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[4], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *phoneNumberServiceProtobufClient) ReleasePhoneNumbers(ctx context.Context, in *ReleasePhoneNumbersRequest) (*ReleasePhoneNumbersResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "PhoneNumberService")
	ctx = ctxsetters.WithMethodName(ctx, "ReleasePhoneNumbers")
	caller := c.callReleasePhoneNumbers
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ReleasePhoneNumbersRequest) (*ReleasePhoneNumbersResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ReleasePhoneNumbersRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ReleasePhoneNumbersRequest) when calling interceptor")
					}
					return c.callReleasePhoneNumbers(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ReleasePhoneNumbersResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ReleasePhoneNumbersResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *phoneNumberServiceProtobufClient) callReleasePhoneNumbers(ctx context.Context, in *ReleasePhoneNumbersRequest) (*ReleasePhoneNumbersResponse, error) {
	out := new(ReleasePhoneNumbersResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[5], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ==============================
// PhoneNumberService JSON Client
// ==============================

type phoneNumberServiceJSONClient struct {
	client      HTTPClient
	urls        [6]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewPhoneNumberServiceJSONClient creates a JSON client that implements the PhoneNumberService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewPhoneNumberServiceJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) PhoneNumberService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "livekit", "PhoneNumberService")
	urls := [6]string{
		serviceURL + "SearchPhoneNumbers",
		serviceURL + "PurchasePhoneNumber",
		serviceURL + "ListPhoneNumbers",
		serviceURL + "GetPhoneNumber",
		serviceURL + "UpdatePhoneNumber",
		serviceURL + "ReleasePhoneNumbers",
	}

	return &phoneNumberServiceJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *phoneNumberServiceJSONClient) SearchPhoneNumbers(ctx context.Context, in *SearchPhoneNumbersRequest) (*SearchPhoneNumbersResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "PhoneNumberService")
	ctx = ctxsetters.WithMethodName(ctx, "SearchPhoneNumbers")
	caller := c.callSearchPhoneNumbers
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *SearchPhoneNumbersRequest) (*SearchPhoneNumbersResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SearchPhoneNumbersRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SearchPhoneNumbersRequest) when calling interceptor")
					}
					return c.callSearchPhoneNumbers(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SearchPhoneNumbersResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SearchPhoneNumbersResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *phoneNumberServiceJSONClient) callSearchPhoneNumbers(ctx context.Context, in *SearchPhoneNumbersRequest) (*SearchPhoneNumbersResponse, error) {
	out := new(SearchPhoneNumbersResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *phoneNumberServiceJSONClient) PurchasePhoneNumber(ctx context.Context, in *PurchasePhoneNumberRequest) (*PurchasePhoneNumberResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "PhoneNumberService")
	ctx = ctxsetters.WithMethodName(ctx, "PurchasePhoneNumber")
	caller := c.callPurchasePhoneNumber
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *PurchasePhoneNumberRequest) (*PurchasePhoneNumberResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*PurchasePhoneNumberRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*PurchasePhoneNumberRequest) when calling interceptor")
					}
					return c.callPurchasePhoneNumber(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*PurchasePhoneNumberResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*PurchasePhoneNumberResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *phoneNumberServiceJSONClient) callPurchasePhoneNumber(ctx context.Context, in *PurchasePhoneNumberRequest) (*PurchasePhoneNumberResponse, error) {
	out := new(PurchasePhoneNumberResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *phoneNumberServiceJSONClient) ListPhoneNumbers(ctx context.Context, in *ListPhoneNumbersRequest) (*ListPhoneNumbersResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "PhoneNumberService")
	ctx = ctxsetters.WithMethodName(ctx, "ListPhoneNumbers")
	caller := c.callListPhoneNumbers
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListPhoneNumbersRequest) (*ListPhoneNumbersResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListPhoneNumbersRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListPhoneNumbersRequest) when calling interceptor")
					}
					return c.callListPhoneNumbers(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListPhoneNumbersResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListPhoneNumbersResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *phoneNumberServiceJSONClient) callListPhoneNumbers(ctx context.Context, in *ListPhoneNumbersRequest) (*ListPhoneNumbersResponse, error) {
	out := new(ListPhoneNumbersResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *phoneNumberServiceJSONClient) GetPhoneNumber(ctx context.Context, in *GetPhoneNumberRequest) (*GetPhoneNumberResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "PhoneNumberService")
	ctx = ctxsetters.WithMethodName(ctx, "GetPhoneNumber")
	caller := c.callGetPhoneNumber
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetPhoneNumberRequest) (*GetPhoneNumberResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetPhoneNumberRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetPhoneNumberRequest) when calling interceptor")
					}
					return c.callGetPhoneNumber(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetPhoneNumberResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetPhoneNumberResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *phoneNumberServiceJSONClient) callGetPhoneNumber(ctx context.Context, in *GetPhoneNumberRequest) (*GetPhoneNumberResponse, error) {
	out := new(GetPhoneNumberResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *phoneNumberServiceJSONClient) UpdatePhoneNumber(ctx context.Context, in *UpdatePhoneNumberRequest) (*UpdatePhoneNumberResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "PhoneNumberService")
	ctx = ctxsetters.WithMethodName(ctx, "UpdatePhoneNumber")
	caller := c.callUpdatePhoneNumber
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UpdatePhoneNumberRequest) (*UpdatePhoneNumberResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdatePhoneNumberRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdatePhoneNumberRequest) when calling interceptor")
					}
					return c.callUpdatePhoneNumber(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*UpdatePhoneNumberResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*UpdatePhoneNumberResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *phoneNumberServiceJSONClient) callUpdatePhoneNumber(ctx context.Context, in *UpdatePhoneNumberRequest) (*UpdatePhoneNumberResponse, error) {
	out := new(UpdatePhoneNumberResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[4], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *phoneNumberServiceJSONClient) ReleasePhoneNumbers(ctx context.Context, in *ReleasePhoneNumbersRequest) (*ReleasePhoneNumbersResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "PhoneNumberService")
	ctx = ctxsetters.WithMethodName(ctx, "ReleasePhoneNumbers")
	caller := c.callReleasePhoneNumbers
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ReleasePhoneNumbersRequest) (*ReleasePhoneNumbersResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ReleasePhoneNumbersRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ReleasePhoneNumbersRequest) when calling interceptor")
					}
					return c.callReleasePhoneNumbers(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ReleasePhoneNumbersResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ReleasePhoneNumbersResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *phoneNumberServiceJSONClient) callReleasePhoneNumbers(ctx context.Context, in *ReleasePhoneNumbersRequest) (*ReleasePhoneNumbersResponse, error) {
	out := new(ReleasePhoneNumbersResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[5], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// =================================
// PhoneNumberService Server Handler
// =================================

type phoneNumberServiceServer struct {
	PhoneNumberService
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewPhoneNumberServiceServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewPhoneNumberServiceServer(svc PhoneNumberService, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &phoneNumberServiceServer{
		PhoneNumberService: svc,
		hooks:              serverOpts.Hooks,
		interceptor:        twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:         pathPrefix,
		jsonSkipDefaults:   jsonSkipDefaults,
		jsonCamelCase:      jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *phoneNumberServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *phoneNumberServiceServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// PhoneNumberServicePathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const PhoneNumberServicePathPrefix = "/twirp/livekit.PhoneNumberService/"

func (s *phoneNumberServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "livekit")
	ctx = ctxsetters.WithServiceName(ctx, "PhoneNumberService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "livekit.PhoneNumberService" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "SearchPhoneNumbers":
		s.serveSearchPhoneNumbers(ctx, resp, req)
		return
	case "PurchasePhoneNumber":
		s.servePurchasePhoneNumber(ctx, resp, req)
		return
	case "ListPhoneNumbers":
		s.serveListPhoneNumbers(ctx, resp, req)
		return
	case "GetPhoneNumber":
		s.serveGetPhoneNumber(ctx, resp, req)
		return
	case "UpdatePhoneNumber":
		s.serveUpdatePhoneNumber(ctx, resp, req)
		return
	case "ReleasePhoneNumbers":
		s.serveReleasePhoneNumbers(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *phoneNumberServiceServer) serveSearchPhoneNumbers(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveSearchPhoneNumbersJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveSearchPhoneNumbersProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *phoneNumberServiceServer) serveSearchPhoneNumbersJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "SearchPhoneNumbers")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(SearchPhoneNumbersRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.PhoneNumberService.SearchPhoneNumbers
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *SearchPhoneNumbersRequest) (*SearchPhoneNumbersResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SearchPhoneNumbersRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SearchPhoneNumbersRequest) when calling interceptor")
					}
					return s.PhoneNumberService.SearchPhoneNumbers(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SearchPhoneNumbersResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SearchPhoneNumbersResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *SearchPhoneNumbersResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *SearchPhoneNumbersResponse and nil error while calling SearchPhoneNumbers. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *phoneNumberServiceServer) serveSearchPhoneNumbersProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "SearchPhoneNumbers")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(SearchPhoneNumbersRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.PhoneNumberService.SearchPhoneNumbers
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *SearchPhoneNumbersRequest) (*SearchPhoneNumbersResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SearchPhoneNumbersRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SearchPhoneNumbersRequest) when calling interceptor")
					}
					return s.PhoneNumberService.SearchPhoneNumbers(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SearchPhoneNumbersResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SearchPhoneNumbersResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *SearchPhoneNumbersResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *SearchPhoneNumbersResponse and nil error while calling SearchPhoneNumbers. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *phoneNumberServiceServer) servePurchasePhoneNumber(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.servePurchasePhoneNumberJSON(ctx, resp, req)
	case "application/protobuf":
		s.servePurchasePhoneNumberProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *phoneNumberServiceServer) servePurchasePhoneNumberJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "PurchasePhoneNumber")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(PurchasePhoneNumberRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.PhoneNumberService.PurchasePhoneNumber
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *PurchasePhoneNumberRequest) (*PurchasePhoneNumberResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*PurchasePhoneNumberRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*PurchasePhoneNumberRequest) when calling interceptor")
					}
					return s.PhoneNumberService.PurchasePhoneNumber(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*PurchasePhoneNumberResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*PurchasePhoneNumberResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *PurchasePhoneNumberResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *PurchasePhoneNumberResponse and nil error while calling PurchasePhoneNumber. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *phoneNumberServiceServer) servePurchasePhoneNumberProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "PurchasePhoneNumber")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(PurchasePhoneNumberRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.PhoneNumberService.PurchasePhoneNumber
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *PurchasePhoneNumberRequest) (*PurchasePhoneNumberResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*PurchasePhoneNumberRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*PurchasePhoneNumberRequest) when calling interceptor")
					}
					return s.PhoneNumberService.PurchasePhoneNumber(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*PurchasePhoneNumberResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*PurchasePhoneNumberResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *PurchasePhoneNumberResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *PurchasePhoneNumberResponse and nil error while calling PurchasePhoneNumber. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *phoneNumberServiceServer) serveListPhoneNumbers(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveListPhoneNumbersJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveListPhoneNumbersProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *phoneNumberServiceServer) serveListPhoneNumbersJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListPhoneNumbers")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(ListPhoneNumbersRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.PhoneNumberService.ListPhoneNumbers
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListPhoneNumbersRequest) (*ListPhoneNumbersResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListPhoneNumbersRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListPhoneNumbersRequest) when calling interceptor")
					}
					return s.PhoneNumberService.ListPhoneNumbers(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListPhoneNumbersResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListPhoneNumbersResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ListPhoneNumbersResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListPhoneNumbersResponse and nil error while calling ListPhoneNumbers. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *phoneNumberServiceServer) serveListPhoneNumbersProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListPhoneNumbers")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(ListPhoneNumbersRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.PhoneNumberService.ListPhoneNumbers
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListPhoneNumbersRequest) (*ListPhoneNumbersResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListPhoneNumbersRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListPhoneNumbersRequest) when calling interceptor")
					}
					return s.PhoneNumberService.ListPhoneNumbers(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListPhoneNumbersResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListPhoneNumbersResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ListPhoneNumbersResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListPhoneNumbersResponse and nil error while calling ListPhoneNumbers. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *phoneNumberServiceServer) serveGetPhoneNumber(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetPhoneNumberJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetPhoneNumberProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *phoneNumberServiceServer) serveGetPhoneNumberJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetPhoneNumber")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(GetPhoneNumberRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.PhoneNumberService.GetPhoneNumber
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetPhoneNumberRequest) (*GetPhoneNumberResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetPhoneNumberRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetPhoneNumberRequest) when calling interceptor")
					}
					return s.PhoneNumberService.GetPhoneNumber(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetPhoneNumberResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetPhoneNumberResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetPhoneNumberResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetPhoneNumberResponse and nil error while calling GetPhoneNumber. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *phoneNumberServiceServer) serveGetPhoneNumberProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetPhoneNumber")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(GetPhoneNumberRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.PhoneNumberService.GetPhoneNumber
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetPhoneNumberRequest) (*GetPhoneNumberResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetPhoneNumberRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetPhoneNumberRequest) when calling interceptor")
					}
					return s.PhoneNumberService.GetPhoneNumber(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetPhoneNumberResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetPhoneNumberResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetPhoneNumberResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetPhoneNumberResponse and nil error while calling GetPhoneNumber. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *phoneNumberServiceServer) serveUpdatePhoneNumber(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveUpdatePhoneNumberJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveUpdatePhoneNumberProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *phoneNumberServiceServer) serveUpdatePhoneNumberJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UpdatePhoneNumber")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(UpdatePhoneNumberRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.PhoneNumberService.UpdatePhoneNumber
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UpdatePhoneNumberRequest) (*UpdatePhoneNumberResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdatePhoneNumberRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdatePhoneNumberRequest) when calling interceptor")
					}
					return s.PhoneNumberService.UpdatePhoneNumber(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*UpdatePhoneNumberResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*UpdatePhoneNumberResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *UpdatePhoneNumberResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *UpdatePhoneNumberResponse and nil error while calling UpdatePhoneNumber. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *phoneNumberServiceServer) serveUpdatePhoneNumberProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UpdatePhoneNumber")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(UpdatePhoneNumberRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.PhoneNumberService.UpdatePhoneNumber
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UpdatePhoneNumberRequest) (*UpdatePhoneNumberResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdatePhoneNumberRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdatePhoneNumberRequest) when calling interceptor")
					}
					return s.PhoneNumberService.UpdatePhoneNumber(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*UpdatePhoneNumberResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*UpdatePhoneNumberResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *UpdatePhoneNumberResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *UpdatePhoneNumberResponse and nil error while calling UpdatePhoneNumber. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *phoneNumberServiceServer) serveReleasePhoneNumbers(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveReleasePhoneNumbersJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveReleasePhoneNumbersProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *phoneNumberServiceServer) serveReleasePhoneNumbersJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ReleasePhoneNumbers")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(ReleasePhoneNumbersRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.PhoneNumberService.ReleasePhoneNumbers
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ReleasePhoneNumbersRequest) (*ReleasePhoneNumbersResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ReleasePhoneNumbersRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ReleasePhoneNumbersRequest) when calling interceptor")
					}
					return s.PhoneNumberService.ReleasePhoneNumbers(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ReleasePhoneNumbersResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ReleasePhoneNumbersResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ReleasePhoneNumbersResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ReleasePhoneNumbersResponse and nil error while calling ReleasePhoneNumbers. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *phoneNumberServiceServer) serveReleasePhoneNumbersProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ReleasePhoneNumbers")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(ReleasePhoneNumbersRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.PhoneNumberService.ReleasePhoneNumbers
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ReleasePhoneNumbersRequest) (*ReleasePhoneNumbersResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ReleasePhoneNumbersRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ReleasePhoneNumbersRequest) when calling interceptor")
					}
					return s.PhoneNumberService.ReleasePhoneNumbers(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ReleasePhoneNumbersResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ReleasePhoneNumbersResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ReleasePhoneNumbersResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ReleasePhoneNumbersResponse and nil error while calling ReleasePhoneNumbers. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *phoneNumberServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor6, 0
}

func (s *phoneNumberServiceServer) ProtocGenTwirpVersion() string {
	return "v8.1.3"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *phoneNumberServiceServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "livekit", "PhoneNumberService")
}

var twirpFileDescriptor6 = []byte{
	// 1157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xdf, 0x6e, 0xe3, 0xc4,
	0x17, 0xce, 0x24, 0x4d, 0xb7, 0x39, 0x49, 0xdb, 0x74, 0xb6, 0xbb, 0x75, 0xdd, 0xed, 0x36, 0xeb,
	0xfe, 0xf4, 0x53, 0x54, 0xd4, 0x54, 0x94, 0xd5, 0xa2, 0x0a, 0x2e, 0x48, 0x5a, 0x77, 0x1b, 0x91,
	0x4d, 0x83, 0x93, 0x02, 0x8b, 0x90, 0x46, 0x8e, 0x33, 0x9b, 0x8e, 0xd6, 0xb1, 0x8d, 0x3d, 0x59,
	0x51, 0xee, 0x91, 0x56, 0x88, 0x0b, 0xc4, 0x2d, 0x4f, 0xc0, 0x4b, 0xf0, 0x02, 0xbc, 0x04, 0x8f,
	0x82, 0x3c, 0x76, 0x5c, 0xa7, 0xb6, 0xd3, 0x0b, 0x90, 0xb8, 0x4b, 0xce, 0xbf, 0xf9, 0xe6, 0xf3,
	0x77, 0xce, 0x19, 0x90, 0x4d, 0xf6, 0x8e, 0xbe, 0x65, 0x9c, 0x38, 0xd7, 0xb6, 0x45, 0x89, 0x35,
	0x9d, 0x0c, 0xa9, 0xdb, 0x70, 0x5c, 0x9b, 0xdb, 0xf8, 0x41, 0xe8, 0x93, 0xf7, 0xc6, 0xb6, 0x3d,
	0x36, 0xe9, 0x91, 0x30, 0x0f, 0xa7, 0x6f, 0x8e, 0x38, 0x9b, 0x50, 0x8f, 0xeb, 0x13, 0x27, 0x88,
	0x94, 0x37, 0x67, 0x55, 0x26, 0xf6, 0x88, 0x9a, 0x5e, 0x60, 0x55, 0xfe, 0x42, 0xb0, 0xdd, 0xa7,
	0xba, 0x6b, 0x5c, 0xf7, 0xfc, 0xe2, 0x5d, 0x51, 0xdb, 0xd3, 0xe8, 0x77, 0x53, 0xea, 0x71, 0xfc,
	0x0c, 0x2a, 0x86, 0x3d, 0xb5, 0xb8, 0x7b, 0x43, 0x0c, 0x7b, 0x44, 0x25, 0x54, 0x43, 0xf5, 0x92,
	0x56, 0x0e, 0x6d, 0xa7, 0xf6, 0x88, 0xe2, 0x1a, 0x94, 0x74, 0x97, 0xea, 0x81, 0x3f, 0xef, 0xfb,
	0x2f, 0x72, 0xda, 0x8a, 0x6f, 0xf2, 0xdd, 0xef, 0x11, 0xc2, 0xdb, 0x50, 0x34, 0xd9, 0x84, 0x71,
	0xa9, 0x50, 0x43, 0xf5, 0xe2, 0x05, 0xd2, 0x82, 0xbf, 0xbe, 0xeb, 0x53, 0x00, 0x47, 0x1f, 0x53,
	0xc2, 0xed, 0xb7, 0xd4, 0x92, 0x96, 0x6a, 0xa8, 0x5e, 0x3e, 0x96, 0x1a, 0x21, 0xd0, 0xc6, 0xc0,
	0xb7, 0xf6, 0xf4, 0x31, 0xb3, 0x74, 0xce, 0x6c, 0xeb, 0x22, 0xaf, 0x95, 0xfc, 0x68, 0x61, 0x7e,
	0x8f, 0x50, 0xab, 0x02, 0x40, 0xa2, 0xb3, 0x5b, 0x2b, 0xb0, 0x4c, 0x44, 0xe1, 0xd6, 0x2a, 0x94,
	0xc9, 0x6d, 0x59, 0xe5, 0x27, 0x04, 0x72, 0xda, 0x15, 0x3d, 0xc7, 0xb6, 0x3c, 0x8a, 0x0f, 0xa0,
	0xc8, 0x38, 0x9d, 0x78, 0x12, 0xaa, 0x15, 0xea, 0xe5, 0xe3, 0xcd, 0xe8, 0xf8, 0x58, 0xb4, 0x16,
	0x84, 0xe0, 0xcf, 0x60, 0xdd, 0xa2, 0xdf, 0xf3, 0x58, 0x75, 0x71, 0xe5, 0x05, 0xa0, 0xb5, 0x55,
	0x3f, 0xa1, 0x37, 0x83, 0xad, 0xfc, 0x82, 0x40, 0xee, 0x4d, 0x5d, 0xe3, 0x5a, 0xf7, 0x68, 0xfc,
	0x80, 0x90, 0xf0, 0x7d, 0x58, 0x8d, 0x7f, 0xe4, 0x00, 0x54, 0x49, 0xab, 0x38, 0x31, 0xe4, 0xf8,
	0x39, 0x6c, 0x7a, 0xcc, 0x21, 0x23, 0xe6, 0x39, 0x3a, 0x37, 0xae, 0x89, 0x3b, 0x35, 0x29, 0x61,
	0xa3, 0x88, 0xfd, 0x0d, 0x8f, 0x39, 0x67, 0xa1, 0x53, 0x9b, 0x9a, 0xb4, 0x3d, 0xf2, 0xd9, 0xda,
	0x82, 0x47, 0x24, 0x2d, 0x4d, 0xf9, 0x1a, 0x76, 0x52, 0x11, 0x85, 0xfc, 0x9c, 0xa4, 0x41, 0xca,
	0xe2, 0x69, 0x0e, 0xa8, 0xf2, 0x6b, 0x1e, 0xb6, 0x3a, 0xcc, 0xe3, 0x69, 0xd2, 0x8a, 0x54, 0x81,
	0x84, 0x2a, 0x72, 0x31, 0x55, 0xbc, 0x80, 0x15, 0x8f, 0xeb, 0x7c, 0xea, 0x51, 0x4f, 0xca, 0xd7,
	0x0a, 0xf5, 0xb5, 0x63, 0x39, 0xed, 0xb0, 0xbe, 0x88, 0xd1, 0xa2, 0xd8, 0x3b, 0x6a, 0x2a, 0xdc,
	0xa3, 0x26, 0x34, 0xaf, 0xa6, 0x4c, 0x56, 0x97, 0x04, 0xab, 0xf9, 0x0c, 0x56, 0xb3, 0x54, 0x97,
	0x4d, 0xf7, 0xef, 0x08, 0xa4, 0x24, 0x29, 0xff, 0x85, 0x18, 0xf1, 0x1e, 0x94, 0xb9, 0xcd, 0x75,
	0x93, 0x88, 0x86, 0x0e, 0xfa, 0x53, 0x03, 0x61, 0x3a, 0xf5, 0x2d, 0x8a, 0x09, 0x8f, 0x5e, 0x52,
	0x9e, 0xa2, 0xd3, 0x87, 0x90, 0x67, 0xa3, 0x60, 0x1c, 0x5c, 0xe4, 0xb4, 0x3c, 0xf3, 0xb9, 0xc0,
	0xff, 0x87, 0x4a, 0x5c, 0x29, 0xa1, 0x1e, 0x91, 0x56, 0x8e, 0x89, 0xc2, 0xe7, 0xac, 0x08, 0x05,
	0xc2, 0x46, 0xad, 0x75, 0x58, 0x9d, 0x9b, 0x68, 0xca, 0x17, 0xf0, 0xf8, 0xee, 0x69, 0x21, 0x2d,
	0x1f, 0xdf, 0xa9, 0x8c, 0xc4, 0x3d, 0xd3, 0xd9, 0x89, 0x9f, 0xa6, 0xfc, 0x81, 0x40, 0xba, 0x72,
	0x46, 0x3a, 0xa7, 0xff, 0xf2, 0x25, 0x32, 0xe5, 0x52, 0x58, 0x28, 0x97, 0x8c, 0xab, 0x67, 0xab,
	0x65, 0x00, 0xdb, 0x29, 0xf8, 0xff, 0x29, 0x2d, 0x7d, 0x90, 0x35, 0x6a, 0xd2, 0xf9, 0x8e, 0x8f,
	0x5a, 0xb3, 0x0a, 0x05, 0x36, 0x9a, 0x8d, 0x1e, 0xff, 0x67, 0x72, 0x2c, 0xe5, 0x93, 0x63, 0x49,
	0xd9, 0x85, 0x9d, 0xd4, 0xa2, 0x01, 0x58, 0xe5, 0xc7, 0x22, 0x94, 0x63, 0x0e, 0xbc, 0x76, 0xcb,
	0xbe, 0xcf, 0xbd, 0x2f, 0x46, 0xfa, 0xe1, 0x8b, 0xe7, 0xe4, 0x8d, 0xed, 0x4e, 0x74, 0x1e, 0xf0,
	0xae, 0x81, 0x6f, 0x3a, 0x17, 0x96, 0xc4, 0x32, 0x2a, 0x24, 0x97, 0xd1, 0x4e, 0x7c, 0x19, 0x89,
	0xc6, 0xbd, 0x5d, 0x45, 0xf8, 0x04, 0xca, 0x01, 0x7c, 0xc2, 0x6f, 0x1c, 0x2a, 0x15, 0x6b, 0xa8,
	0xbe, 0x16, 0xeb, 0x95, 0x18, 0xb6, 0xc1, 0x8d, 0x43, 0x35, 0xb0, 0xa2, 0xdf, 0x58, 0x86, 0x15,
	0xd3, 0x36, 0x74, 0x93, 0xf1, 0x1b, 0x69, 0x39, 0x28, 0x3b, 0xfb, 0x8f, 0x1f, 0xc3, 0xb2, 0x4b,
	0xc7, 0xcc, 0xb6, 0xa4, 0x07, 0xc2, 0x13, 0xfe, 0xc3, 0xbb, 0x00, 0x9e, 0xa3, 0x4f, 0x88, 0x67,
	0xd8, 0x2e, 0x95, 0x56, 0x6a, 0xa8, 0x8e, 0xb4, 0x92, 0x6f, 0xe9, 0xfb, 0x06, 0x7c, 0x02, 0x60,
	0xb8, 0x54, 0xe7, 0x74, 0x44, 0x74, 0x2e, 0x95, 0xc4, 0x97, 0x93, 0x1b, 0xc1, 0x12, 0x6f, 0xcc,
	0x96, 0x78, 0x63, 0x30, 0x5b, 0xe2, 0x5a, 0x29, 0x8c, 0x6e, 0x72, 0x3f, 0x75, 0x2a, 0x34, 0x21,
	0x52, 0xe1, 0xfe, 0xd4, 0x30, 0xba, 0xc9, 0xb1, 0x02, 0x15, 0x43, 0x77, 0xf4, 0x21, 0x33, 0x19,
	0x67, 0xd4, 0x93, 0xca, 0xc1, 0x77, 0x8c, 0xdb, 0xf0, 0x31, 0x2c, 0x07, 0x23, 0x55, 0xaa, 0x08,
	0x8a, 0x16, 0x0d, 0xdf, 0x30, 0x12, 0x7f, 0x02, 0x65, 0xdd, 0xf3, 0xd8, 0xd8, 0x0a, 0x30, 0xad,
	0xde, 0x8b, 0x09, 0x66, 0xe1, 0x4d, 0xee, 0x27, 0xbb, 0x81, 0x70, 0x44, 0xf2, 0xda, 0xfd, 0xc9,
	0xb3, 0xf0, 0x26, 0xc7, 0x47, 0x19, 0x7d, 0xb8, 0x2e, 0x3e, 0x46, 0xb2, 0x0b, 0x0f, 0x7e, 0x43,
	0xb0, 0x91, 0xb8, 0x08, 0xde, 0x87, 0xbd, 0xde, 0xc5, 0x65, 0x57, 0x25, 0xdd, 0xab, 0x57, 0x2d,
	0x55, 0x23, 0xfd, 0x41, 0x73, 0x70, 0xd5, 0x27, 0x57, 0xdd, 0x7e, 0x4f, 0x3d, 0x6d, 0x9f, 0xb7,
	0xd5, 0xb3, 0x6a, 0x0e, 0x3f, 0x05, 0x39, 0x2d, 0xa8, 0x79, 0x3a, 0x68, 0x7f, 0xa9, 0x56, 0x11,
	0xde, 0x83, 0x9d, 0x34, 0x7f, 0x4f, 0xed, 0x9e, 0xb5, 0xbb, 0x2f, 0xab, 0x79, 0x5c, 0x83, 0x27,
	0x69, 0x01, 0x9a, 0xda, 0x51, 0x9b, 0x7d, 0xf5, 0xac, 0x5a, 0x38, 0xf8, 0x19, 0xc1, 0xfa, 0x1d,
	0x25, 0xe2, 0x5d, 0xd8, 0x9e, 0xcb, 0x1a, 0xbc, 0xee, 0xa9, 0xe4, 0xaa, 0xfb, 0x79, 0xf7, 0xf2,
	0xab, 0x6e, 0x35, 0x87, 0x9f, 0x80, 0x94, 0x74, 0xbf, 0xba, 0x6c, 0xb5, 0x3b, 0x3e, 0xa6, 0x1d,
	0xd8, 0x4a, 0x7a, 0x3b, 0x97, 0xa7, 0xcd, 0x4e, 0x35, 0x9f, 0x00, 0x2c, 0x9c, 0x83, 0xcb, 0x4e,
	0x87, 0x9c, 0x6b, 0xaa, 0x5a, 0x2d, 0x1c, 0xff, 0xb9, 0x04, 0x38, 0x4e, 0x16, 0x75, 0xdf, 0x31,
	0x83, 0x62, 0x02, 0x38, 0xf9, 0xa2, 0xc2, 0x4a, 0x24, 0x94, 0xcc, 0x17, 0xa5, 0xbc, 0xbf, 0x30,
	0x26, 0x1c, 0x15, 0x39, 0x3c, 0x84, 0x87, 0x29, 0x6f, 0x12, 0x7c, 0x9b, 0x9d, 0xfd, 0x86, 0x92,
	0xff, 0xb7, 0x38, 0x28, 0x3a, 0xe3, 0x35, 0x54, 0xef, 0xee, 0x61, 0x5c, 0x8b, 0x72, 0x33, 0xde,
	0x2d, 0xf2, 0xb3, 0x05, 0x11, 0x51, 0xe9, 0x3e, 0xac, 0xcd, 0x6f, 0x32, 0xfc, 0x34, 0x4a, 0x4b,
	0x5d, 0xa8, 0xf2, 0x5e, 0xa6, 0x3f, 0x2a, 0xfa, 0x2d, 0x6c, 0x24, 0x56, 0x01, 0xbe, 0x85, 0x93,
	0xb5, 0xe6, 0x64, 0x65, 0x51, 0x48, 0x9c, 0xf1, 0x94, 0xe9, 0x1d, 0x63, 0x3c, 0x7b, 0x61, 0xc4,
	0x18, 0x5f, 0xb4, 0x00, 0x72, 0xad, 0xc3, 0x6f, 0x3e, 0x18, 0x33, 0x7e, 0x3d, 0x1d, 0x36, 0x0c,
	0x7b, 0x72, 0xe4, 0xd2, 0x1f, 0xd8, 0x21, 0xb3, 0x8f, 0xc2, 0xdc, 0x43, 0xd1, 0xe8, 0x86, 0x6d,
	0xce, 0x0c, 0xc3, 0x65, 0x61, 0xf9, 0xe8, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x09, 0x12, 0x5a,
	0xd7, 0x00, 0x0d, 0x00, 0x00,
}
